exclude :test_engines_free, 'needs investigation'
exclude :test_openssl_engine_builtin, 'needs investigation'
exclude :test_openssl_engine_by_id_string, 'needs investigation'
exclude :test_openssl_engine_cipher_rc4, 'needs investigation'
exclude :test_openssl_engine_digest_sha1, 'needs investigation'
exclude :test_openssl_engine_id_name_inspect, 'needs investigation'