exclude :test_legacy_error_classes, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271"
exclude :test_raw_initialize_errors, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271"
exclude :test_s_generate_parameters_with_block, "work in progress"
exclude :test_s_read_der_then_pem, "PKey.read returns different DER encoding on master"
exclude :test_s_read_passphrase, "PKeyError: Could not parse PKey: unsupported"
