exclude :test_digest_by_oid_and_name, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, Unsupported digest algorithm (RSA-SHA256)"
exclude :test_digests, "work in progress"
exclude :test_initialize, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, uninitialized constant OpenSSL::Digest::DigestError"
exclude :test_sha3, "work in progress"
exclude :test_sha512_truncate, "work in progress"
