exclude :test_add_entry_placing, "work in progress"
exclude :test_dup, "work in progress"
exclude :test_spaceship, "work in progress"
exclude :test_to_s, "work in progress"
exclude :test_to_utf8, "work in progress"
