exclude :test_akiski, "work in progress"
exclude :test_crl_uris_multiple_general_names, "work in progress"
exclude :test_crl_uris_no_uris, "work in progress"
exclude :test_inspect, "inspect format differs from CRuby (subject= vs subject=#<OpenSSL::X509::Name>)"
exclude :test_load_file_certificate_der, "work in progress"
exclude :test_load_file_empty_pem, "work in progress"
exclude :test_load_file_fullchain_garbage, "work in progress"
exclude :test_load_file_fullchain_pem, "work in progress"
exclude :test_read_der_then_pem, "work in progress"
exclude :test_sign_and_verify_ed25519, "work in progress"
exclude :test_sign_and_verify_nil_digest, "undefined method 'generate_key' for module OpenSSL::PKey"
