exclude :test_add_file_path, "work in progress"
exclude :test_store_new, "work in progress"
exclude :test_verify_callback, "work in progress"
exclude :test_verify_simple, "work in progress"
exclude :test_verify_with_crl, "work in progress"
