exclude :test_engines_free, 'OpenSSL::Engine not implemented!'
exclude :test_openssl_engine_builtin, 'OpenSSL::Engine not implemented!'
exclude :test_openssl_engine_by_id_string, 'OpenSSL::Engine not implemented!'
exclude :test_openssl_engine_cipher_rc4, 'OpenSSL::Engine not implemented!'
exclude :test_openssl_engine_digest_sha1, 'OpenSSL::Engine not implemented!'
exclude :test_openssl_engine_id_name_inspect, 'OpenSSL::Engine not implemented!'
