exclude :test_check_key, "work in progress"
exclude :test_ECPrivateKey_encrypted, "PKeyError expected, got ECError - error class hierarchy mismatch with Ruby 4.0 tests"
exclude :test_ec_point, "work in progress"
exclude :test_ec_point_add, "work in progress"
exclude :test_ec_point_mul, "work in progress"
exclude :test_generate, "PKeyError expected, got ECError - error class hierarchy mismatch with Ruby 4.0 tests"
exclude :test_generate_key, "PKeyError expected, got ECError - error class hierarchy mismatch with Ruby 4.0 tests"
exclude :test_sign_verify_raw, "work in progress"
exclude :test_small_curve, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, null curve name"
