exclude :test_client_session, "needs investigation"
exclude :test_ctx_client_session_cb, "needs investigation"
exclude :test_ctx_server_session_cb, "needs investigation"
exclude :test_server_session, "needs investigation"
exclude :test_session, "needs investigation"
exclude :test_session_equals, "needs investigation"
exclude :test_session_time, "needs investigation"
exclude :test_session_timeout, "needs investigation"