exclude :test_basic_asn1data, "work in progress"
exclude :test_basic_constructed, "work in progress"
exclude :test_decode_constructed_overread, "work in progress"
exclude :test_end_of_content, "work in progress"
exclude :test_generalizedtime, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271"
exclude :test_object_identifier, "work in progress"
exclude :test_recursive_octet_string_indefinite_length, "work in progress"
exclude :test_recursive_octet_string_parse, "work in progress"
exclude :test_sequence, "work in progress"
exclude :test_set, "work in progress"
exclude :test_utctime, "ASN1Error expected but nothing raised"
