/* The following code was generated by JFlex 1.3.5 on 18.12.01 18:18 */

/*
*/
package org.jruby.scanner;

import java.io.*;
import java.util.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 18.12.01 18:18 from the specification file
 * <tt>file:/home/jpetersen/development/jruby/scanner/Ruby.flex</tt>
 */
public class RubyScanner implements TokenTypes, IRubyScanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int EXPR_CMDARG = 3;
  final public static int EXPR_MID = 3;
  final public static int HEREDOC = 2;
  final public static int EXPR_ARG = 4;
  final public static int STRING = 2;
  final public static int EXPR_FNAME = 3;
  final public static int EXPR_CLASS = 2;
  final public static int EXPR_DOT = 3;
  final public static int EXPR_ENDARG = 3;
  final public static int MLCOMMENT = 1;
  final public static int YYINITIAL = 0;
  final public static int EXPR_END = 3;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\16\1\0"+
    "\1\4\6\0\1\17\21\0\1\20\1\5\1\15\43\0\1\6\1\0"+
    "\1\13\1\7\1\0\1\10\1\0\1\11\4\0\1\12\17\0\1\14"+
    "\uff81\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    17,    34,    51,    68,    85,    34,   102,   119,   136, 
      153,   170,   187,   204,   204,   221,   238,   170,   255,    34, 
      272,   289,    34,    34,    34,   306,    34,    34,    34,   323, 
      340,   357,   374,    34,   391,    34,   408,    34,    34,    34, 
       34,   425,   442,   459,   476,   493,    34,   510,   527,   544, 
      544,   561,    34
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\0\1\6\2\7\1\10\1\11\7\0\1\12\1\13"+
    "\1\14\1\15\1\16\2\17\2\16\1\20\13\16\26\0"+
    "\1\21\7\0\1\12\1\13\1\14\1\15\5\0\1\21"+
    "\7\0\1\12\1\13\1\22\1\15\2\0\1\7\16\0"+
    "\1\10\1\23\1\24\16\10\5\0\1\25\1\26\5\0"+
    "\1\27\1\30\10\0\1\31\7\0\1\32\10\0\1\33"+
    "\6\0\1\34\11\0\1\35\11\0\1\36\6\0\1\37"+
    "\12\0\1\40\1\16\1\41\1\42\25\16\1\43\11\16"+
    "\5\0\1\25\6\0\1\27\1\30\5\0\1\24\23\0"+
    "\1\44\22\0\1\45\16\0\1\46\20\0\1\47\30\0"+
    "\1\50\10\0\1\51\15\0\1\42\16\0\12\16\1\52"+
    "\6\16\10\0\1\53\10\0\13\16\1\54\5\16\11\0"+
    "\1\55\7\0\1\16\1\56\2\57\15\16\12\0\1\60"+
    "\10\0\1\57\17\0\1\61\1\62\1\63\15\0\1\63"+
    "\1\64\1\62\17\63\1\64\1\65\16\63\2\0\1\65"+
    "\16\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  8,  0,  0,  1,  9,  0,  1,  1,  1,  1,  1,  0,  1,  0, 
     1,  1,  1,  9,  1,  0,  9,  9,  9,  1,  9,  9,  9,  1,  1,  1, 
     1,  9,  0,  9,  0,  9,  9,  9,  9,  0,  0,  0,  0,  1,  9,  0, 
     1,  1,  0,  1,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /* user code: */
   private transient StringBuffer mlCommentText = null;

   private transient ArrayList scannerListener = new ArrayList();
   
   private IToken createToken(int type) {
      return new Token(type, yyline + 1, yycolumn + 1, null);
   }

   private IToken createToken(int type, Object data) {
      return new Token(type, yyline + 1, yycolumn + 1, data);
   }

   private void warn(String message) {
      Iterator iter = scannerListener.iterator();
       while (iter.hasNext()) {
         ((IScannerListener)iter.next()).scannerWarning(yyline + 1, yycolumn + 1, message);
      }
   }

   private void error(String message) {
      Iterator iter = scannerListener.iterator();
      while (iter.hasNext()) {
         ((IScannerListener)iter.next()).scannerError(yyline + 1, yycolumn + 1, message);
      }
   }

   public void addScannerListener(IScannerListener listener) {
      scannerListener.add(listener);
   }

   public void removeScannerListener(IScannerListener listener) {
      scannerListener.remove(listener);
   }

   /** Method to test the Scanner
    *
    */
   public static void main(String args[]) throws IOException {
      RubyScanner scanner = new RubyScanner(System.in);

      IToken next = scanner.getNextToken();
      while (next != null) {
         System.out.println(next);
	 next = scanner.getNextToken();
      }
   }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public RubyScanner(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public RubyScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[578];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 62) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public IToken getNextToken() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 28: 
          {  yybegin(YYINITIAL); return createToken(OP_ASSIGN, "*");  }
        case 54: break;
        case 45: 
        case 46: 
          {  yybegin(YYINITIAL); mlCommentText.append(yytext()); return createToken(MULTILINE_COMMENT, mlCommentText.toString());  }
        case 55: break;
        case 18: 
        case 19: 
          {  return createToken(LINE_COMMENT, yytext());  }
        case 56: break;
        case 48: 
        case 49: 
        case 51: 
        case 52: 
          {  yybegin(MLCOMMENT); mlCommentText = new StringBuffer(yytext());  }
        case 57: break;
        case 39: 
          {  yybegin(YYINITIAL); return createToken(OP_CMP);  }
        case 58: break;
        case 35: 
          {  yybegin(YYINITIAL); return createToken(OP_EQQ);  }
        case 59: break;
        case 30: 
          {  yybegin(YYINITIAL); return createToken(OP_LEQ);  }
        case 60: break;
        case 29: 
          {  yybegin(YYINITIAL); return createToken(OP_POW);  }
        case 61: break;
        case 11: 
          {   yybegin(YYINITIAL); return createToken(OP_STAR);  }
        case 62: break;
        case 10: 
          {  yybegin(YYINITIAL); return createToken(OP_NOT);  }
        case 63: break;
        case 20: 
          {  yybegin(YYINITIAL); return createToken(OP_EQ);  }
        case 64: break;
        case 24: 
          {  yybegin(YYINITIAL); return createToken(OP_GEQ);  }
        case 65: break;
        case 26: 
          {  yybegin(YYINITIAL); return createToken(OP_NEQ);  }
        case 66: break;
        case 40: 
          {  yybegin(YYINITIAL); return createToken(OP_ASSIGN, "<<");  }
        case 67: break;
        case 38: 
          {  yybegin(YYINITIAL); return createToken(OP_ASSIGN, "**");  }
        case 68: break;
        case 37: 
          {  yybegin(YYINITIAL); return createToken(OP_ASSIGN, ">>");  }
        case 69: break;
        case 31: 
          {  yybegin(YYINITIAL); return createToken(OP_LSHFT);  }
        case 70: break;
        case 17: 
          {  yybegin(YYINITIAL); warn("'*' interpreted as argument prefix"); return createToken(OP_STAR);  }
        case 71: break;
        case 22: 
          {  yybegin(YYINITIAL); return createToken(OP_MATCH);  }
        case 72: break;
        case 23: 
          {  yybegin(YYINITIAL); return createToken(OP_ASSOC);  }
        case 73: break;
        case 25: 
          {  yybegin(YYINITIAL); return createToken(OP_RSHFT);  }
        case 74: break;
        case 14: 
        case 32: 
        case 33: 
          {  mlCommentText.append(yytext());  }
        case 75: break;
        case 12: 
          {  yybegin(YYINITIAL); return createToken(OP_LESSER);  }
        case 76: break;
        case 9: 
          {  yybegin(YYINITIAL); return createToken(OP_GREATER);  }
        case 77: break;
        case 8: 
        case 16: 
          {  yybegin(YYINITIAL); return createToken(OP_ASSIGN);  }
        case 78: break;
        case 27: 
          {  yybegin(YYINITIAL); return createToken(OP_NMATCH);  }
        case 79: break;
        case 5: 
        case 6: 
          {  }
        case 80: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            return null;
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
