# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise64"
  
  # Bootstrap with a script
  config.vm.provision :shell, :path => 'tool/truffle/vagrant_bootstrap.sh'

  # Remote debug port
  config.vm.network "forwarded_port", guest: 5005, host: 5005

  config.vm.provider "virtualbox" do |vb|
    
    # Set the vm memory
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    
  end

end
