exclude :"test_changes_after_commit_are_discarded", "needs investigation"
exclude :"test_changes_are_not_written_on_abort", "needs investigation"
exclude :"test_data_should_be_loaded_correctly_when_in_readonly_mode", "needs investigation"
exclude :"test_pstore_files_are_accessed_as_binary_files", "needs investigation"
exclude :"test_data_should_be_loaded_correctly_when_in_readwrite_mode", "needs investigation"
exclude :"test_nested_transaction_raises_error", "needs investigation"
exclude :"test_opening_new_file_in_readwrite_mode_should_result_in_empty_values", "needs investigation"
exclude :"test_thread_safe", "needs investigation"
