exclude :test_ipv4_compat, "needs investigation"
exclude :test_ipv4_mapped, "needs investigation"
exclude :test_s_new, "needs investigation"
exclude :test_ip6_arpa, "needs investigation"
exclude :test_ip6_int, "needs investigation"
exclude :test_reverse, "needs investigation"
exclude :test_s_new_ntoh, "needs investigation"
exclude :test_to_s, "needs investigation"
