exclude :test_each_pair, "needs investigation"
exclude :test_method_missing, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_delete_field, "needs investigation"
exclude :test_equality, "needs investigation"
exclude :test_frozen, "needs investigation"
exclude :test_getter, "needs investigation"
