exclude :test_casecmp2, "needs investigation"
exclude :test_count, "needs investigation"
exclude :test_header, "needs investigation"
exclude :test_hex, "needs investigation"
exclude :test_is_mbc_newline, "needs investigation"
exclude :test_oct, "needs investigation"
exclude :test_regexp_match, "needs investigation"
exclude :test_split_awk, "needs investigation"
exclude :test_succ, "needs investigation"
exclude :test_sym_eq, "needs investigation"
exclude :test_slice, "needs investigation"
exclude :test_slice! , "needs investigation"
