exclude :test_decode64, "needs investigation"
exclude :test_sample, "needs investigation"
exclude :test_strict_decode64, "needs investigation"
exclude :test_urlsafe_decode64, "needs investigation"
exclude :"test_urlsafe_decode64_unpadded", "needs investigation"
