exclude :test_MATCH, "needs investigation"
exclude :test_MOD, "needs investigation"
exclude :test_bytes, "needs investigation"
exclude :test_chars, "needs investigation"
exclude :test_chomp, "needs investigation"
exclude :test_codepoints, "needs investigation"
exclude :test_count, "needs investigation"
exclude :test_delete, "needs investigation"
exclude :test_eq_tilde_can_be_overridden, "needs investigation"
exclude :test_gsub_enumerator, "needs investigation"
exclude :test_hash_random, "needs investigation"
exclude :test_index, "needs investigation"
exclude :test_lines, "needs investigation"
exclude :test_match_method, "needs investigation"
exclude :test_mod_check, "needs investigation"
exclude :test_partition, "needs investigation"
exclude :test_regexp_match_subclass, "needs investigation"
exclude :test_respond_to, "needs investigation"
exclude :test_rindex, "needs investigation"
exclude :test_rpartition, "needs investigation"
exclude :test_rstrip, "needs investigation"
exclude :test_scan, "needs investigation"
exclude :test_sub, "needs investigation"
exclude :test_sum_2, "needs investigation"
exclude :test_to_i, "needs investigation"
exclude :test_to_id, "needs investigation"
exclude :test_to_str, "needs investigation"
exclude :test_upto_nonalnum, "needs investigation"
exclude :test_upto_numeric, "needs investigation"
exclude :test_ASET, "needs investigation"
exclude :test_center, "needs investigation"
exclude :test_each, "needs investigation"
exclude :test_each_line, "needs investigation"
exclude :test_gsub, "needs investigation"
exclude :test_ljust, "needs investigation"
exclude :test_prepend, "needs investigation"
exclude :test_rjust, "needs investigation"
exclude :test_shared_force_encoding, "needs investigation"
exclude :test_slice, "needs investigation"
exclude :test_splice, "needs investigation"
exclude :test_split, "needs investigation"
exclude :test_sum, "needs investigation"
exclude :test_ASET , "needs investigation"
exclude :test_center , "needs investigation"
exclude :test_chomp! , "needs investigation"
exclude :test_each , "needs investigation"
exclude :test_each_line , "needs investigation"
exclude :test_gsub , "needs investigation"
exclude :test_ljust , "needs investigation"
exclude :test_prepend , "needs investigation"
exclude :test_rjust , "needs investigation"
exclude :test_shared_force_encoding , "needs investigation"
exclude :test_slice! , "needs investigation"
exclude :test_splice! , "needs investigation"
exclude :test_split , "needs investigation"
exclude :test_sum , "needs investigation"
exclude :test_clone, "needs investigation"
exclude :test_clone, "needs investigation"
exclude :test_strip, "needs investigation"
exclude :"test_ascii_incomat_inspect", "needs investigation"
exclude :"test_crypt", "needs investigation"
exclude :"test_dummy_inspect", "needs investigation"
exclude :"test_s_new", "needs investigation"
exclude :"test_setter", "needs investigation"
exclude :"test_split_invalid_argument", "needs investigation"
