exclude :test_defined_empty_argument, "needs investigation"
exclude :test_must_ascii_compatible, "needs investigation"
exclude :test_script_lines, "needs investigation"
exclude :test_syntax_ext, "needs investigation"
exclude :test_syntax_lib, "needs investigation"
exclude :test_syntax_sample, "needs investigation"
exclude :test_syntax_test, "needs investigation"
exclude :test__END___cr , "needs investigation"
exclude :test_brace_block_after_blockcall_colon_no_arg , "needs investigation"
exclude :test_brace_block_after_blockcall_dot_no_arg , "needs investigation"
exclude :test_brace_block_after_blockcall_dot_with_arg , "needs investigation"
exclude :test_cmd_symbol_after_keyword , "needs investigation"
exclude :test_cmd_symbol_in_string , "needs investigation"
exclude :test_cmd_symbol_singleton_class , "needs investigation"
exclude :test_cmd_symbol_superclass , "needs investigation"
exclude :test_constant_reassignment_nested , "needs investigation"
exclude :test_constant_reassignment_toplevel , "needs investigation"
exclude :test_do_block_after_blockcall_colon_no_arg , "needs investigation"
exclude :test_do_block_after_blockcall_colon_with_arg , "needs investigation"
exclude :test_do_block_after_blockcall_dot_no_arg , "needs investigation"
exclude :test_do_block_after_blockcall_dot_with_arg , "needs investigation"
exclude :test_do_block_in_call_args , "needs investigation"
exclude :test_do_block_in_cmdarg , "needs investigation"
exclude :test_do_block_in_cmdarg_begin , "needs investigation"
exclude :test_duplicated_arg , "needs investigation"
exclude :test_duplicated_kw , "needs investigation"
exclude :test_duplicated_kw_kwrest , "needs investigation"
exclude :test_duplicated_opt , "needs investigation"
exclude :test_duplicated_opt_kw , "needs investigation"
exclude :test_duplicated_opt_kwrest , "needs investigation"
exclude :test_duplicated_opt_post , "needs investigation"
exclude :test_duplicated_opt_rest , "needs investigation"
exclude :test_duplicated_rest , "needs investigation"
exclude :test_duplicated_rest_kw , "needs investigation"
exclude :test_duplicated_rest_kwrest , "needs investigation"
exclude :test_duplicated_rest_opt , "needs investigation"
exclude :test_duplicated_rest_post , "needs investigation"
exclude :test_duplicated_when , "needs investigation"
exclude :test_error_message_encoding , "needs investigation"
exclude :test_heredoc_cr , "needs investigation"
exclude :test_integer_suffix , "needs investigation"
exclude :test_keyword_splat , "needs investigation"
exclude :test_lineno_command_call_quote , "needs investigation"
exclude :test_lineno_operation_brace_block , "needs investigation"
exclude :test_optional_self_reference , "needs investigation"
exclude :test_unassignable , "needs investigation"
exclude :test_unexpected_fraction , "needs investigation"
exclude :test_value_of_def , "needs investigation"
exclude :test_warn_balanced , "needs investigation"
exclude :test_warning_for_cr , "needs investigation"
exclude :test_brace_block_after_blockcall_colon_with_arg, "needs investigation"
exclude :test_newline_in_block_parameters, "needs investigation"
exclude :test_warn_unreachable, "needs investigation"
exclude :test_bad_kwarg, "needs investigation"
exclude :test_do_block_in_lambda, "needs investigation"
exclude :test_keyword_self_reference, "needs investigation"
exclude :test_keyword_empty_splat, "needs investigation"
exclude :test_null_range_cmdarg, "needs investigation"
exclude :test_too_big_nth_ref, "needs investigation"
exclude :"test_keyword_duplicated_splat", "needs investigation"
exclude :test_keyword_duplicated, "needs investigation"

