exclude :test_brace_lambda_source_location, "needs investigation"
exclude :test_call_with_block, "needs investigation"
exclude :test_do_lambda_source_location, "needs investigation"
exclude :test_lambda_as_iterator, "needs investigation"
exclude :"test_yield_relaxed(array,&lambda)", "needs investigation"
exclude :"test_yield_relaxed(to_ary,&lambda)", "needs investigation"
