exclude :test_compatible_p, "needs investigation"
exclude :test_errinfo_after_autoload, "needs investigation"
exclude :test_find, "needs investigation"
exclude :test_replicate, "needs investigation"
exclude :test_singleton, "needs investigation"
exclude :test_marshal, "needs investigation"
