exclude :test_ceil , "needs investigation"
exclude :test_floor , "needs investigation"
exclude :test_power , "needs investigation"
exclude :test_quo , "needs investigation"
exclude :test_round , "needs investigation"
exclude :test_truncate , "needs investigation"
