exclude :test_eof_0_seek, "needs investigation"
exclude :test_eof_1_seek, "needs investigation"
exclude :test_frozen, "needs investigation"
exclude :test_frozen_string, "needs investigation"
exclude :test_gets, "needs investigation"
exclude :test_gets2, "needs investigation"
exclude :test_lineno, "needs investigation"
exclude :test_pos, "needs investigation"
exclude :test_read_nonblock_no_exceptions, "needs investigation"
exclude :test_reopen, "needs investigation"
exclude :test_seek, "needs investigation"
exclude :test_seek_beyond_eof, "needs investigation"
exclude :test_ungetbyte, "needs investigation"
exclude :test_ungetc, "needs investigation"
exclude :test_write_infection, "needs investigation"
exclude :test_write_nonblock_no_exceptions, "needs investigation"
exclude :test_dup, "needs investigation"
exclude :test_each, "needs investigation"
exclude :test_each_byte, "needs investigation"
exclude :test_each_char, "needs investigation"
exclude :test_each_codepoint, "needs investigation"
exclude :test_getbyte, "needs investigation"
exclude :test_overwrite, "needs investigation"
exclude :test_readbyte, "needs investigation"
exclude :test_readchar, "needs investigation"
exclude :test_readlines, "needs investigation"
exclude :test_truncate, "needs investigation"
exclude :test_ungetc_pos, "needs investigation"
exclude :test_dup , "needs investigation"
exclude :test_each , "needs investigation"
exclude :test_each_byte , "needs investigation"
exclude :test_each_char , "needs investigation"
exclude :test_each_codepoint , "needs investigation"
exclude :test_getbyte , "needs investigation"
exclude :test_overwrite , "needs investigation"
exclude :test_readbyte , "needs investigation"
exclude :test_readchar , "needs investigation"
exclude :test_readlines , "needs investigation"
exclude :test_truncate , "needs investigation"
exclude :test_ungetc_pos , "needs investigation"
exclude :"test_close", "needs investigation"
exclude :"test_close_read", "needs investigation"
exclude :"test_close_write", "needs investigation"
exclude :"test_read", "needs investigation"
exclude :"test_set_encoding", "needs investigation"
exclude :"test_sysread", "needs investigation"
exclude :"test_ungetbyte_padding", "needs investigation"
exclude :"test_ungetc_padding", "needs investigation"
exclude :"test_binmode", "needs investigation"
