exclude :test_global_variable_0, "needs investigation"
exclude :test_local_variables2, "needs investigation"
exclude :test_local_variables3, "needs investigation"
exclude :test_shadowing_block_local_variables, "needs investigation"
exclude :test_shadowing_local_variables, "needs investigation"
exclude :test_variable, "needs investigation"
exclude :test_special_constant_ivars, "needs investigation"
