exclude :test_sub_matchdata, "needs investigation"
exclude :test_ascend_446, "needs investigation"
exclude :test_atime, "needs investigation"
exclude :test_binread, "needs investigation"
exclude :test_binwrite, "needs investigation"
exclude :test_birthtime, "needs investigation"
exclude :test_blockdev, "needs investigation"
exclude :test_chardev, "needs investigation"
exclude :test_children, "needs investigation"
exclude :test_chmod, "needs investigation"
exclude :test_chown, "needs investigation"
exclude :test_cleanpath_aggressive_48, "needs investigation"
exclude :test_cleanpath_aggressive_53, "needs investigation"
exclude :test_cleanpath_aggressive_54, "needs investigation"
exclude :test_cleanpath_aggressive_55, "needs investigation"
exclude :test_cleanpath_aggressive_64, "needs investigation"
exclude :test_cleanpath_aggressive_69, "needs investigation"
exclude :test_cleanpath_aggressive_70, "needs investigation"
exclude :test_cleanpath_aggressive_71, "needs investigation"
exclude :test_cleanpath_aggressive_72, "needs investigation"
exclude :test_cleanpath_aggressive_78, "needs investigation"
exclude :test_cleanpath_aggressive_84, "needs investigation"
exclude :test_cleanpath_aggressive_85, "needs investigation"
exclude :test_cleanpath_aggressive_86, "needs investigation"
exclude :test_cleanpath_aggressive_87, "needs investigation"
exclude :test_cleanpath_aggressive_88, "needs investigation"
exclude :test_cleanpath_conservative_104, "needs investigation"
exclude :test_cleanpath_conservative_105, "needs investigation"
exclude :test_cleanpath_conservative_106, "needs investigation"
exclude :test_cleanpath_conservative_114, "needs investigation"
exclude :test_cleanpath_conservative_119, "needs investigation"
exclude :test_cleanpath_conservative_120, "needs investigation"
exclude :test_cleanpath_conservative_121, "needs investigation"
exclude :test_cleanpath_conservative_122, "needs investigation"
exclude :test_cleanpath_conservative_128, "needs investigation"
exclude :test_cleanpath_conservative_138, "needs investigation"
exclude :test_cleanpath_conservative_99, "needs investigation"
exclude :test_ctime, "needs investigation"
exclude :test_del_trailing_separator_159, "needs investigation"
exclude :test_del_trailing_separator_188, "needs investigation"
exclude :test_descend_437, "needs investigation"
exclude :test_directory, "needs investigation"
exclude :test_each_child, "needs investigation"
exclude :test_each_entry, "needs investigation"
exclude :test_each_line, "needs investigation"
exclude :test_entries, "needs investigation"
exclude :test_executable, "needs investigation"
exclude :test_executable_real, "needs investigation"
exclude :test_exist, "needs investigation"
exclude :test_expand_path, "needs investigation"
exclude :test_extname, "needs investigation"
exclude :test_file, "needs investigation"
exclude :test_file_dirname, "needs investigation"
exclude :test_file_extname, "needs investigation"
exclude :test_file_join, "needs investigation"
exclude :test_file_split, "needs investigation"
exclude :test_find, "needs investigation"
exclude :test_fnmatch, "needs investigation"
exclude :test_freeze_and_taint, "needs investigation"
exclude :test_ftype, "needs investigation"
exclude :test_grpowned, "needs investigation"
exclude :test_kernel_open, "needs investigation"
exclude :test_lchmod, "needs investigation"
exclude :test_lchown, "needs investigation"
exclude :test_lstat, "needs investigation"
exclude :test_make_link, "needs investigation"
exclude :test_make_symlink, "needs investigation"
exclude :test_matchop, "needs investigation"
exclude :test_mkdir, "needs investigation"
exclude :test_mkpath, "needs investigation"
exclude :test_mountpoint, "needs investigation"
exclude :test_mountpoint_enoent, "needs investigation"
exclude :test_mtime, "needs investigation"
exclude :test_open, "needs investigation"
exclude :test_opendir, "needs investigation"
exclude :test_owned, "needs investigation"
exclude :test_parent_236, "needs investigation"
exclude :test_parent_237, "needs investigation"
exclude :test_pathsubext_527, "needs investigation"
exclude :test_pathsubext_528, "needs investigation"
exclude :test_pathsubext_529, "needs investigation"
exclude :test_pathsubext_530, "needs investigation"
exclude :test_pathsubext_531, "needs investigation"
exclude :test_pathsubext_532, "needs investigation"
exclude :test_pathsubext_533, "needs investigation"
exclude :test_pathsubext_534, "needs investigation"
exclude :test_pathsubext_535, "needs investigation"
exclude :test_pathsubext_536, "needs investigation"
exclude :test_pipe, "needs investigation"
exclude :test_plus_213, "needs investigation"
exclude :test_read, "needs investigation"
exclude :test_readable, "needs investigation"
exclude :test_readable_real, "needs investigation"
exclude :test_readlines, "needs investigation"
exclude :test_readlink, "needs investigation"
exclude :test_realdirpath, "needs investigation"
exclude :test_realpath, "needs investigation"
exclude :test_relative_path_from_328, "needs investigation"
exclude :test_relative_path_from_329, "needs investigation"
exclude :test_relative_path_from_casefold, "needs investigation"
exclude :test_rename, "needs investigation"
exclude :test_rmdir, "needs investigation"
exclude :test_rmtree, "needs investigation"
exclude :test_s_glob, "needs investigation"
exclude :test_setgid, "needs investigation"
exclude :test_setuid, "needs investigation"
exclude :test_size, "needs investigation"
exclude :test_slash, "needs investigation"
exclude :test_socket, "needs investigation"
exclude :test_split, "needs investigation"
exclude :test_stat, "needs investigation"
exclude :test_sticky, "needs investigation"
exclude :test_symlink, "needs investigation"
exclude :test_sysopen, "needs investigation"
exclude :test_truncate, "needs investigation"
exclude :test_unlink, "needs investigation"
exclude :test_utime, "needs investigation"
exclude :test_world_readable, "needs investigation"
exclude :test_world_writable, "needs investigation"
exclude :test_writable, "needs investigation"
exclude :test_writable_real, "needs investigation"
exclude :test_write, "needs investigation"
exclude :test_zero, "needs investigation"
exclude :test_dirname, "needs investigation"
exclude :test_relative_path_from_299, "needs investigation"
exclude :test_relative_path_from_300, "needs investigation"
exclude :test_relative_path_from_301, "needs investigation"
exclude :test_relative_path_from_302, "needs investigation"
exclude :test_relative_path_from_314, "needs investigation"
exclude :test_relative_path_from_315, "needs investigation"
exclude :test_relative_path_from_316, "needs investigation"
exclude :test_relative_path_from_319, "needs investigation"
exclude :test_relative_path_from_321, "needs investigation"
exclude :test_blockdev? , "needs investigation"
exclude :test_chardev? , "needs investigation"
exclude :test_directory? , "needs investigation"
exclude :test_dirname , "needs investigation"
exclude :test_executable? , "needs investigation"
exclude :test_executable_real? , "needs investigation"
exclude :test_exist? , "needs investigation"
exclude :test_file? , "needs investigation"
exclude :test_fnmatch? , "needs investigation"
exclude :test_grpowned? , "needs investigation"
exclude :test_mountpoint? , "needs investigation"
exclude :test_owned? , "needs investigation"
exclude :test_pipe? , "needs investigation"
exclude :test_readable? , "needs investigation"
exclude :test_readable_real? , "needs investigation"
exclude :test_relative_path_from_299 , "needs investigation"
exclude :test_relative_path_from_300 , "needs investigation"
exclude :test_relative_path_from_301 , "needs investigation"
exclude :test_relative_path_from_302 , "needs investigation"
exclude :test_relative_path_from_314 , "needs investigation"
exclude :test_relative_path_from_315 , "needs investigation"
exclude :test_relative_path_from_316 , "needs investigation"
exclude :test_relative_path_from_319 , "needs investigation"
exclude :test_relative_path_from_321 , "needs investigation"
exclude :test_setgid? , "needs investigation"
exclude :test_setuid? , "needs investigation"
exclude :test_size? , "needs investigation"
exclude :test_socket? , "needs investigation"
exclude :test_sticky? , "needs investigation"
exclude :test_symlink? , "needs investigation"
exclude :test_world_readable? , "needs investigation"
exclude :test_world_writable? , "needs investigation"
exclude :test_writable? , "needs investigation"
exclude :test_writable_real? , "needs investigation"
exclude :test_zero? , "needs investigation"
exclude :"test_ascend_447", "needs investigation"
exclude :"test_ascend_448", "needs investigation"
exclude :"test_ascend_449", "needs investigation"
exclude :"test_ascend_450", "needs investigation"
exclude :"test_blockless_ascend_is_enumerator", "needs investigation"
exclude :"test_blockless_descend_is_enumerator", "needs investigation"
exclude :"test_descend_438", "needs investigation"
exclude :"test_descend_439", "needs investigation"
exclude :"test_descend_440", "needs investigation"
exclude :"test_descend_441", "needs investigation"
