exclude :test_encode_with_invalid_chars, "needs investigation"
exclude :test_encodings, "needs investigation"
exclude :test_errors, "needs investigation"
exclude :test_fallback, "needs investigation"
exclude :test_fallback_hash_default, "needs investigation"
exclude :test_fallback_method, "needs investigation"
exclude :test_fallback_proc, "needs investigation"
exclude :test_gb18030, "needs investigation"
exclude :test_invalid_ignore, "needs investigation"
exclude :test_invalid_replace, "needs investigation"
exclude :test_invalid_replace_string, "needs investigation"
exclude :test_iso_2022_jp, "needs investigation"
exclude :test_noargument, "needs investigation"
exclude :test_pseudo_encoding_inspect, "needs investigation"
exclude :test_to_cp50221, "needs investigation"
exclude :test_undef_replace_string, "needs investigation"
exclude :test_unicode_public_review_issue_121, "needs investigation"
exclude :test_utf8_mac, "needs investigation"
exclude :test_valid_dummy_encoding, "needs investigation"
exclude :test_utf_16, "needs investigation"
exclude :test_utf_32, "needs investigation"
exclude :test_utf_16 , "needs investigation"
exclude :test_utf_32 , "needs investigation"
exclude :"test_pseudo_encoding_inspect(UTF-16)", "needs investigation"
exclude :"test_pseudo_encoding_inspect(UTF-32)", "needs investigation"
exclude :"test_loading_race", "needs investigation"
