exclude :test_with_filename, "needs investigation"
exclude :test_with_filename_and_safe_level, "needs investigation"
exclude :test_without_filename, "needs investigation"
exclude :test_without_filename_with_safe_level, "needs investigation"
exclude :test_literal_encoding, "needs investigation"
exclude :test_method_with_encoding, "needs investigation"
exclude :test_recognize_magic_comment, "needs investigation"
exclude :test_result_encoding, "needs investigation"
exclude :test_html_escape, "java.lang.NullPointerException at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.translate(ExceptionTranslatingNode.java:159)"
