exclude :test_anonymous_message, "needs investigation"
exclude :test_catch_throw_in_require, "needs investigation"
exclude :test_cause, "needs investigation"
exclude :test_cause_reraised, "needs investigation"
exclude :test_cause_with_no_arguments, "needs investigation"
exclude :test_equal, "needs investigation"
exclude :test_errinfo_in_debug, "needs investigation"
exclude :test_errno, "needs investigation"
exclude :test_exception_in_ensure, "needs investigation"
exclude :test_exception_in_exception_equal, "needs investigation"
exclude :test_exception_in_name_error_to_str, "needs investigation"
exclude :test_exit_success_p, "this was exiting the test process"
