exclude :test_AREF, "needs investigation"
exclude :test_generic_regexp, "needs investigation"
exclude :test_getch, "needs investigation"
exclude :test_matched, "needs investigation"
exclude :test_pos_unicode, "needs investigation"
exclude :test_post_match, "needs investigation"
exclude :test_s_allocate, "needs investigation"
exclude :test_bol, "needs investigation"
exclude :test_bol? , "needs investigation"
