exclude :test_assign_private_self, "needs investigation"
exclude :test_massign, "needs investigation"
exclude :test_multi, "needs investigation"
exclude :test_nested_massign, "needs investigation"
exclude :test_next, "needs investigation"
exclude :test_return, "needs investigation"
exclude :test_to_ary_splat, "needs investigation"
exclude :test_yield, "needs investigation"
