exclude :test_Integer, "needs investigation"
exclude :test_bitwise_and_with_integer_mimic_object, "needs investigation"
exclude :test_bitwise_or_with_integer_mimic_object, "needs investigation"
exclude :test_bitwise_xor_with_integer_mimic_object, "needs investigation"
exclude :test_lshift, "needs investigation"
exclude :test_rshift, "needs investigation"
exclude :test_downto, "needs investigation"
exclude :test_downto , "needs investigation"
