exclude :test_ascii_incomat_inspect, "needs investigation"
exclude :test_call, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_symbol_encoding, "needs investigation"
exclude :test_symbol_gc_1, "needs investigation"
exclude :test_to_proc, "needs investigation"
exclude :test_hash_redefinition, "hangs"
exclude :test_symbol_fstr_leak, "hangs"
exclude :"test_to_proc_arg", "needs investigation"
exclude :"test_to_proc_for_hash_each", "needs investigation"
exclude :"test_to_proc_new_proc", "needs investigation"
exclude :"test_to_proc_no_method", "needs investigation"
exclude :"test_to_proc_yield", "needs investigation"
exclude :"test_to_proc_binding", "needs investigation"
exclude :"test_to_proc_iseq", "needs investigation"
