exclude :test_add, "needs investigation"
exclude :test_div, "needs investigation"
exclude :test_mul, "needs investigation"
exclude :test_scalar_add, "needs investigation"
exclude :test_scalar_div, "needs investigation"
exclude :test_scalar_mul, "needs investigation"
exclude :test_scalar_pow, "needs investigation"
exclude :test_scalar_sub, "needs investigation"
exclude :test_sub, "needs investigation"
exclude :test_laplace_expansion, "needs investigation"
exclude :test_eigensystem, "needs investigation"
exclude :test_exp, "needs investigation"
exclude :test_inverse, "needs investigation"
exclude :test_lup, "needs investigation"
exclude :test_rank, "needs investigation"
exclude :test_rank2, "needs investigation"
exclude :test_eigensystem , "needs investigation"
exclude :test_exp , "needs investigation"
exclude :test_inverse , "needs investigation"
exclude :test_lup , "needs investigation"
exclude :test_rank , "needs investigation"
exclude :test_rank2 , "needs investigation"
exclude :"test_det", "needs investigation"
