exclude :test_eratosthenes_works_fine_after_timeout, "needs investigation"
exclude :test_each, "needs investigation"
exclude :test_each_by_prime_number_theorem, "needs investigation"
exclude :test_enumerator_succ, "needs investigation"
exclude :test_enumerator_with_index, "needs investigation"
