exclude :test_eval_ascii_incompatible, "needs investigation"
exclude :test_eval_basic, "needs investigation"
exclude :test_eval_binding_basic, "needs investigation"
exclude :test_eval_location_fstring, "needs investigation"
exclude :test_eval_orig, "needs investigation"
exclude :test_eval_with_toplevel_binding, "needs investigation"
exclude :test_file_encoding, "needs investigation"
exclude :test_fixnum_instance_eval_cvar, "needs investigation"
exclude :test_gced_binding_block, "needs investigation"
exclude :test_instance_eval_const, "needs investigation"
exclude :test_instance_eval_cvar, "needs investigation"
exclude :test_instance_eval_string_basic, "needs investigation"
exclude :test_module_eval_string_basic, "needs investigation"
exclude :test_nil_instance_eval_cvar, "needs investigation"
exclude :test_cvar_scope_with_instance_eval, "Defining a cvar on Fixnum should apparently define on Object"
