exclude :"test_format_float(%-00.E)", "needs investigation"
exclude :"test_format_float(%.E)", "needs investigation"
exclude :"test_format_float(%0.e)", "needs investigation"
exclude :"test_format_float(%0E)", "needs investigation"
exclude :"test_format_float(%e)", "needs investigation"
exclude :"test_format_integer(%-00.b)", "needs investigation"
exclude :"test_format_integer(%.b)", "needs investigation"
exclude :"test_format_integer(%0.B)", "needs investigation"
exclude :"test_format_integer(%0b)", "needs investigation"
exclude :"test_format_integer(%B)", "needs investigation"
exclude :"test_format_float(% #+-0e)", "needs investigation"
exclude :"test_format_float(% #+0.E)", "needs investigation"
exclude :"test_format_integer(% #+-0B)", "needs investigation"
exclude :"test_format_integer(% #+0.b)", "needs investigation"
