exclude :test_anonymous, "needs investigation"
exclude :test_array, "needs investigation"
exclude :test_array_ivar, "needs investigation"
exclude :test_array_subclass, "needs investigation"
exclude :test_bignum, "needs investigation"
exclude :test_exception, "needs investigation"
exclude :test_exception_subclass, "needs investigation"
exclude :test_extend, "needs investigation"
exclude :test_extend_string, "needs investigation"
exclude :test_false, "needs investigation"
exclude :test_fixnum, "needs investigation"
exclude :test_float, "needs investigation"
exclude :test_float_inf_nan, "needs investigation"
exclude :test_hash_extend, "needs investigation"
exclude :test_hash_ivar, "needs investigation"
exclude :test_hash_subclass, "needs investigation"
exclude :test_hash_subclass_extend, "needs investigation"
exclude :test_marshal, "needs investigation"
exclude :test_object, "needs investigation"
exclude :test_object_extend, "needs investigation"
exclude :test_object_prepend, "needs investigation"
exclude :test_object_subclass, "needs investigation"
exclude :test_object_subclass_extend, "needs investigation"
exclude :test_range, "needs investigation"
exclude :test_range_cyclic, "needs investigation"
exclude :test_range_subclass, "needs investigation"
exclude :test_regexp, "needs investigation"
exclude :test_regexp_subclass, "needs investigation"
exclude :test_singleton, "needs investigation"
exclude :test_string_ivar, "needs investigation"
exclude :test_string_subclass, "needs investigation"
exclude :test_string_subclass_cycle, "needs investigation"
exclude :test_string_subclass_extend, "needs investigation"
exclude :test_struct, "needs investigation"
exclude :test_struct_ivar, "needs investigation"
exclude :test_struct_subclass, "needs investigation"
exclude :test_struct_subclass_extend, "needs investigation"
exclude :test_struct_toplevel, "needs investigation"
exclude :test_time, "needs investigation"
exclude :test_time_in_array, "needs investigation"
exclude :test_time_ivar, "needs investigation"
exclude :test_time_subclass, "needs investigation"
exclude :test_true, "needs investigation"
exclude :test_change_class_name , "needs investigation"
exclude :test_change_struct , "needs investigation"
exclude :test_class , "needs investigation"
exclude :test_class_ivar , "needs investigation"
exclude :test_class_nonascii , "needs investigation"
exclude :test_context_switch , "needs investigation"
exclude :test_continuation , "needs investigation"
exclude :test_dump_buffer , "needs investigation"
exclude :test_hash_default , "needs investigation"
exclude :test_inconsistent_struct , "needs investigation"
exclude :test_marshal_cloned_class , "needs investigation"
exclude :test_marshal_complex , "needs investigation"
exclude :test_marshal_dump , "needs investigation"
exclude :test_marshal_dump_excess_encoding , "needs investigation"
exclude :test_marshal_dump_extra_iv , "needs investigation"
exclude :test_marshal_dump_ivar , "needs investigation"
exclude :test_marshal_dump_struct_ivar , "needs investigation"
exclude :test_marshal_encoding_encoding , "needs investigation"
exclude :test_marshal_flonum_reference , "needs investigation"
exclude :test_marshal_load_ivar , "needs investigation"
exclude :test_marshal_load_should_not_taint_classes , "needs investigation"
exclude :test_marshal_private_class , "needs investigation"
exclude :test_marshal_rational , "needs investigation"
exclude :test_marshal_regexp_encoding , "needs investigation"
exclude :test_marshal_respond_to_arity , "needs investigation"
exclude :test_marshal_string_encoding , "needs investigation"
exclude :test_modify_array_during_dump , "needs investigation"
exclude :test_module_ivar , "needs investigation"
exclude :test_pipe , "needs investigation"
exclude :test_regexp2 , "needs investigation"
exclude :test_struct_invalid_members , "needs investigation"
exclude :test_taint , "needs investigation"
exclude :test_taint_each_object , "needs investigation"
exclude :test_too_long_string , "needs investigation"
exclude :test_userdef_encoding , "needs investigation"
