exclude :test_autoloaded_noload, "needs investigation"
exclude :test_defined, "needs investigation"
exclude :test_defined_impl_specific, "needs investigation"
exclude :test_exception, "needs investigation"
exclude :test_super_toplevel, "needs investigation"
