exclude :test_cannot_convert_into_time_interval, "needs investigation"
exclude :test_custom_exception, "needs investigation"
exclude :test_enumerator_next, "needs investigation"
exclude :test_exit_exception, "needs investigation"
exclude :test_queue, "needs investigation"
exclude :test_rescue_exit, "needs investigation"
exclude :test_skip_rescue, "needs investigation"
exclude :test_timeout, "needs investigation"
