exclude :test_Float, "needs investigation"
exclude :test_cmp, "needs investigation"
exclude :test_cmp_int, "needs investigation"
exclude :test_div, "needs investigation"
exclude :test_floor, "needs investigation"
exclude :test_floor_ceil_round_truncate, "needs investigation"
exclude :test_long_string, "needs investigation"
exclude :test_next_float, "needs investigation"
exclude :test_next_prev_float_zero, "needs investigation"
exclude :test_num2dbl, "needs investigation"
exclude :test_precision, "needs investigation"
exclude :test_prev_float, "needs investigation"
exclude :test_remainder, "needs investigation"
exclude :test_strtod, "needs investigation"
exclude :test_to_s, "needs investigation"
exclude :test_truncate, "needs investigation"
exclude :test_hash_0, "-0.0.hash is not == 0.0.hash currently"
