exclude :test_define_method, "needs investigation"
exclude :test_double_include2, "needs investigation"
exclude :test_from_eval, "needs investigation"
exclude :test_keyword1, "needs investigation"
exclude :test_keyword2, "needs investigation"
exclude :test_optional1, "needs investigation"
exclude :test_optional2, "needs investigation"
exclude :test_optional3, "needs investigation"
exclude :test_optional4, "needs investigation"
exclude :test_optional5, "needs investigation"
exclude :test_super_in_BEGIN, "needs investigation"
exclude :test_super_in_at_exit, "needs investigation"
exclude :test_super_in_instance_eval, "needs investigation"
exclude :test_super_in_instance_eval_with_define_method, "needs investigation"
exclude :test_super_in_module_unbound_method, "needs investigation"
exclude :test_super_in_orphan_block_with_instance_eval, "needs investigation"
exclude :test_super_with_block, "needs investigation"
exclude :test_super_in_END, "needs investigation"
exclude :"test_array2", "regression, related to commits mentioned in https://github.com/jruby/jruby/issues/2963"
exclude :"test_array3", "regression, related to commits mentioned in https://github.com/jruby/jruby/issues/2963"
exclude :"test_array4", "regression, related to commits mentioned in https://github.com/jruby/jruby/issues/2963"
exclude :"test_double2", "regression, related to commits mentioned in https://github.com/jruby/jruby/issues/2963"
