exclude :test_parse_files, "assumes MRI source layout to randomly rip .rb files"
exclude :'test_parse_files:ext', "assumes MRI source layout to randomly rip .rb files"
exclude :'test_parse_files:lib', "assumes MRI source layout to randomly rip .rb files"
exclude :'test_parse_files:sample', "assumes MRI source layout to randomly rip .rb files"
exclude :'test_parse_files:test', "assumes MRI source layout to randomly rip .rb files"
