exclude :test_end_of_script_char, "needs investigation"
exclude :test_heredoc_no_memory_leak, "no working assert_no_memory_leak method"
exclude :test_heredoc_unterminated_interpolation, "needs investigation"
exclude :test_invalid_escape_ctrl_mbchar, "needs investigation"
exclude :test_invalid_escape_ctrl_meta_mbchar, "needs investigation"
exclude :test_invalid_escape_meta_ctrl_mbchar, "needs investigation"
exclude :test_invalid_escape_meta_mbchar, "needs investigation"
exclude :test_invalid_escape_string, "needs investigation"
exclude :test_lexer_scan_with_syntax_error, "needs investigation"
exclude :test_nested_heredoc, "needs investigation"
exclude :test_raise_errors_keyword, "needs investigation"
exclude :test_spaces_at_eof, "needs investigation"
exclude :test_token_aftr_error_heredoc, "needs investigation"
exclude :test_tokenize_with_here_document, "needs investigation"
