exclude :test_block_variables, "RLIMITing causes crash without JVM heap tweaking"
exclude :test_return_out_of_compile_error_no_memory_leak, "no working assert_no_memory_leak method"
exclude :test_return_out_of_warn_no_memory_leak, "no working assert_no_memory_leak method"
exclude :test_warn_mismatched_indentations, "needs investigation"
exclude :test_warning_invalid_magic_comment, "needs investigation"
