exclude :test_anonymous_block_forwarding, "needs investigation"
exclude :test_anonymous_keyword_rest_forwarding, "needs investigation"
exclude :test_anonymous_rest_forwarding, "needs investigation"
exclude :test_args_forward, "needs investigation"
exclude :test_assign_error_backref, "needs investigation"
exclude :test_call_colon2, "needs investigation"
exclude :test_event_coverage, "needs investigation"
exclude :test_return_out_of_compile_error_no_memory_leak, "uses CRuby memory leak detection"
exclude :test_return_out_of_warn_no_memory_leak, "uses CRuby memory leak detection"
exclude :test_warn_duplicated_hash_keys, "needs investigation"
exclude :test_warn_mismatched_indentations, "needs investigation"
exclude :test_warning_duplicated_when_clause, "needs investigation"
exclude :test_warning_invalid_magic_comment, "needs investigation"
