exclude :test_CHAR, "needs investigation"
exclude :test_event_coverage, "needs investigation"
exclude :test_invalid_char, "needs investigation"
exclude :test_invalid_escape, "needs investigation"
exclude :test_invalid_hex_escape_regexp, "needs investigation"
exclude :test_invalid_hex_escape_string, "needs investigation"
exclude :test_words_sep, "needs investigation"
