#-*- mode: ruby -*-

# tell maven to include the jar files into gem
gemspec :include_jars => true

# TODO this clean should be part of upstream when generating 
# the pom for the gemspec 
plugin( :clean ) do
  execute_goals( :clean,
                 :phase => :clean, 
                 :id => 'clean-lib',
                 :filesets => [ { :directory => '${basedir}/lib',
                                  :includes => ['*.jar'] } ],
                 :failOnError => false )
end

properties( 'tesla.dump.pom' => 'pom.xml',
            'tesla.dump.readonly' => true )

# vim: syntax=Ruby
