exclude :test_cmp, "needs investigation"
exclude :test_coerce, "needs investigation"
exclude :test_coerce2, "needs investigation"
exclude :test_conv, "needs investigation"
exclude :test_marshal, "needs investigation"
exclude :test_power_overflow, "consumes much time and memory on JVM"
exclude :test_ratsub, "needs investigation"
