exclude :test_cmp, "needs investigation"
exclude :test_coerce, "needs investigation"
exclude :test_coerce2, "needs investigation"
exclude :test_conv, "needs investigation"
exclude :test_marshal, "needs investigation"
exclude :test_power_of_0, "needs investigation"
exclude :test_power_of_1_and_minus_1, "needs investigation"
exclude :test_power_overflow, "runs long eventually fails, see https://bugs.ruby-lang.org/issues/13242"
exclude :test_ratsub, "needs investigation"
