exclude :test_at, "MRI uses less precision than JRuby, which causes it to produce incorrect values"
exclude :test_at_rational, "MRI uses less precision than JRuby, which causes it to produce incorrect values"
exclude :test_future, "needs investigation"
exclude :test_marshal_nsec_191, "needs investigation"
exclude :test_past, "needs investigation"
exclude :test_plus_type, "needs investigation"
exclude :test_reinitialize, "needs investigation"
exclude :test_strftime_invalid_flags, "needs investigation"
exclude :test_strftime_rational, "needs investigation"
exclude :test_strftime_too_wide, "needs investigation"
exclude :test_time_interval, "needs investigation"
exclude :test_utc_or_local, "needs investigation"
exclude :test_xmlschema, "raising Joda errors recently, #2237"