exclude :test_each_arg, "unfinished in initial 2.6 work, #6161"
exclude :test_generator, "needs investigation"
exclude :test_initialize, "https://github.com/jruby/jruby/issues/7708"
exclude :test_initialize_copy, "needs investigation"
exclude :test_inspect, "unfinished in initial 2.6 work, #6161"
exclude :test_inspect_encoding, "needs investigation"
exclude :test_lazy_chain_under_gc_compact_stress, "GC is not configurable in JRuby"
exclude :test_peek_modify, "needs investigation"
exclude :test_with_index_large_offset, "needs investigation"
exclude :test_with_index_under_gc_compact_stress, "GC is not configurable in JRuby"
