exclude :test_exception_overflow, "runs forever"

exclude :test_BigMath_exp_under_gc_stress, "needs investigation"
exclude :test_BigMath_log_under_gc_stress, "needs investigation"
exclude :test_div, "needs investigation"
exclude :test_exception_underflow, "needs investigation"

exclude :test_global_new_with_float, "needs investigation"
exclude :test_global_new_with_invalid_string, "error change in 2.4?"
exclude :test_limit, "needs investigation"
exclude :test_marshal, "needs investigation"
exclude :test_mult, "error change in 2.4?"
exclude :test_new, "stricter parsing in 2.4"

exclude :test_power_of_negative_infinity, "needs investigation"
exclude :test_power_of_positive_infinity, "needs investigation"
exclude :test_power_of_three, "needs investigation"
exclude :test_power_of_zero, "needs investigation"
exclude :test_power_with_Bignum, "needs investigation"
exclude :test_power_with_prec, "needs investigation"
exclude :test_power_without_prec, "needs investigation"

exclude :test_round_up, "needs investigation"
exclude :test_sqrt_bigdecimal, "needs investigation"
exclude :test_sub, "needs investigation"
exclude :test_sub_bigdecimal, "needs investigation"
exclude :test_thread_local_mode, "needs investigation"
exclude :test_to_f, "needs investigation"
exclude :test_to_special_string, "needs investigation"
exclude :test_zero_p, "needs investigation"
exclude :test_add, "needs investigation"
exclude :test_ctov, "needs investigation"