exclude :test_get, "work in progress"
exclude :test_get_SNI, "work in progress"
exclude :test_get_SNI_failure, "work in progress"
exclude :test_identity_verify_failure, ""
exclude :test_max_version, "missing set_minmax_proto_version for OpenSSL::SSL::SSLContext"
exclude :test_min_version, "missing set_minmax_proto_version for OpenSSL::SSL::SSLContext"
exclude :test_post, "work in progress"
exclude :test_session_reuse, ""
exclude :test_session_reuse_but_expire, "hangs"
exclude :test_skip_hostname_verification, "work in progress"
