exclude :test_copy_entry_symlink, "needs investigation"
exclude :test_cp_r_symlink, "needs investigation"
exclude :test_ln_s, "needs investigation"
exclude :test_ln_sf, "needs investigation"
exclude :test_mv_symlink, "mv tries to canonicalize through bad symlink (#2153)"
exclude :test_uptodate?, "needs investigation"
