exclude :test_classext_memory_leak, "no working assert_no_memory_leak method"
exclude :test_clone_singleton_class_exists, "work in progress"
exclude :test_constant_access_from_method_in_cloned_class, "work in progress"
exclude :test_invalid_retry_from_class_definition, "new LJE behavior or tests in Ruby 2.5"
exclude :test_method_redefinition, "needs investigation"
exclude :test_redefine_private_class, "needs investigation"
exclude :test_redefinition_mismatch, "parser issue with Japanese identifiers (#3679)"
exclude :test_singleton_class_message, "error says class instead of Class"
exclude :test_singleton_class_should_has_own_namespace, "new behavior for 2.3 (#3693)"
exclude :test_subclasses, "work in progress"
exclude :test_uninitialized, "needs investigation"
exclude :test_visibility_inside_method, "work in progress"
