exclude :test_aset, "needs investigation"
exclude :test_assoc, "needs investigation"
exclude :test_delete, "needs investigation"
exclude :test_fetch, "needs investigation"
exclude :test_getenv, "needs investigation"
exclude :test_has_key, "needs investigation"
exclude :test_rehash, "needs investigation"
exclude :test_taint_aref, "expects SAFE security exceptions"
exclude :test_taint_aset_key, "expects SAFE security exceptions"
exclude :test_taint_aset_value, "expects SAFE security exceptions"
exclude :test_taint_assoc, "expects SAFE security exceptions"
exclude :test_taint_fetch, "expects SAFE security exceptions"
exclude :test_taint_key, "expects SAFE security exceptions"
exclude :test_taint_key_p, "expects SAFE security exceptions"
exclude :test_taint_rassoc, "expects SAFE security exceptions"
exclude :test_taint_value_p, "expects SAFE security exceptions"
