exclude :test_dup_warn, "temporarily disabled warning"
exclude :test_initialize, "needs investigation"
exclude :test_invalid_escape_error, "needs investigation"
exclude :test_invalid_fragment, "needs investigation"
exclude :test_match_without_regexp, "matches non-unicode with exception message using regexp, but our messages are always unicode"
exclude :test_named_capture_nonascii, "needs investigation"
exclude :test_once_multithread, "fails intermittently"
exclude :test_to_s, "needs investigation"
exclude :test_unescape, "needs investigation"
