exclude :test_bug_18343, "work in progress"
exclude :test_format_string_modified, "needs investigation"
exclude :test_length_too_big, "needs investigation"
exclude :test_pack_P, "needs investigation"
exclude :test_pack_p, "needs investigation"
exclude :test_pack_resize, "needs investigation"
exclude :test_pack_unpack_M, "needs investigation"
exclude :test_pack_unpack_P2, "needs investigation"
exclude :test_pack_unpack_atmark, "errors differently in JRuby but does not overrun buffer (https://hackerone.com/reports/298246)"
exclude :test_pack_unpack_bB, "needs investigation"
exclude :test_pack_unpack_u, "needs investigation"
exclude :test_short_with_block, "needs investigation"
