exclude :test_brace_lambda_source_location, "broken in compiler (#458)"
exclude :test_create_non_lambda_for_proc_one_level, "https://github.com/jruby/jruby/issues/7707"
exclude :test_create_non_lambda_for_proc_two_levels, "https://github.com/jruby/jruby/issues/7707"
exclude :test_do_lambda_source_location, "broken in compiler (#458)"
exclude :test_location_on_error, "broken in compiler (#458)"
