exclude :test_civil__ex, "work in progress"
exclude :test_commercial__ex, "work in progress"
exclude :test_jd__ex, "work in progress"
exclude :test_memsize, "uses ObjectSpace.memsize_of"
exclude :test_ordinal__ex, "work in progress"
exclude :test_valid_with_invalid_types, "work in progress"
