exclude :test_basename, "needs investigation"
exclude :test_dirname, "needs investigation"
exclude :test_expand_path_encoding, "needs investigation"
exclude :test_expand_path_home_dir_string, "needs investigation"
exclude :test_expand_path_memsize, "uses objspace"
exclude :test_expand_path_returns_tainted_strings_or_not, "needs investigation"
exclude :test_extname, "needs investigation"
exclude :test_join_ascii_incompatible, "needs investigation"
exclude :test_lchmod, "Fails on Linux"
exclude :test_readlink_long_path, "needs investigation"