exclude :test_cannot_reinitialize_class_with_initialize_copy, "broken subprocess logic in setup"
exclude :test_check_inheritable, "needs investigation"
exclude :test_invalid_jump_from_class_definition, "needs investigation"
exclude :test_method_redefinition, "needs investigation"
exclude :test_module_function, "needs investigation"
exclude :test_redefine_private_class, "needs investigation"
exclude :test_redefinition_mismatch, "parser issue with Japanese identifiers (#3679)"
exclude :test_singleton_class_message, "error says object instead of Class"
exclude :test_singleton_class_should_has_own_namespace, "new behavior for 2.3 (#3693)"
exclude :test_uninitialized, "needs investigation"
