exclude :test_argf, "needs investigation"
exclude :test_each_line_limit_0, "needs investigation"
exclude :test_encoding, "needs investigation"
exclude :test_eof, "needs investigation"
exclude :test_filename2, "needs investigation"
exclude :test_inplace2, "needs investigation"
exclude :test_inplace3, "needs investigation"
exclude :test_inplace_ascii_incompatible_path, "needs investigation"
exclude :test_inplace_bug_17117, "needs investigation"
exclude :test_inplace_no_backup, "needs investigation"
exclude :test_inplace_nonascii, "fails on Linux at least"
exclude :test_inplace_rename_impossible, "needs investigation"
exclude :test_inplace_stdin, "needs investigation"
exclude :test_inplace_stdin2, "needs investigation"
exclude :test_lineno, "needs investigation"
exclude :test_lineno2, "needs investigation"
exclude :test_readlines_limit_0, "HANGS"
exclude :test_skip_in_each_char, "needs investigation"
exclude :test_skip_in_each_codepoint, "needs investigation"
exclude :test_to_io, "needs investigation"
exclude :test_wrong_type, "needs investigation"
