exclude :test_attr_source_location, "needs investigation"
exclude :test_dup_clone, "needs investigation"
exclude :test_parameters, "needs investigation"
exclude :test_proc_lambda, "needs investigation"
exclude :test_safe, "needs investigation"
