exclude :test_error, "work in progress"
exclude :test_fatal_in_fiber, "work in progress"
exclude :test_no_valid_cfp, "raises NPE rather than detecting bad context and raising a Ruby error"
exclude :test_prohibit_transfer_to_resuming_fiber, "FiberError expected"
exclude :test_prohibit_transfer_to_yielding_fiber, "FiberError expected"
exclude :test_separate_lastmatch, "work in progress"
exclude :test_terminate_transferred_fiber, "work in progress"
exclude :test_to_s, "work in progress"
