exclude :test_feed, "needs investigation"
exclude :test_feed_before_first_next, "needs investigation"
exclude :test_feed_mixed, "needs investigation"
exclude :test_feed_yielder, "needs investigation"
exclude :test_generator, "needs investigation"
exclude :test_initialize, "needs investigation"
exclude :test_initialize_copy, "needs investigation"
exclude :test_inspect_encoding, "needs investigation"
exclude :test_nested_iteration, "yield called out of block"
exclude :test_next_values, "needs investigation"
exclude :test_peek_modify, "needs investigation"
exclude :test_peek_values, "needs investigation"
exclude :test_rewind_clear_feed, "needs investigation"
exclude :test_with_index_large_offset, "needs investigation"
