exclude :test_atime, "needs investigation"
exclude :test_basename_encoding, "needs investigation"
exclude :test_closed_io_identical_p, "needs investigation"
exclude :test_dirname, "work in progress"
exclude :test_dirname_encoding, "needs investigation"
exclude :test_expand_path_encoding, "needs investigation"
exclude :test_expand_path_home_dir_string, "needs investigation"
exclude :test_expand_path_home_memory_leak_in_base, "no working assert_no_memory_leak method"
exclude :test_expand_path_home_memory_leak_in_path, "no working assert_no_memory_leak method"
exclude :test_expand_path_memsize, "uses objspace"
exclude :test_expand_path_returns_tainted_strings_or_not, "needs investigation"
exclude :test_extname, "needs investigation"
exclude :test_flock_exclusive, "exceeds 10s timeout"
exclude :test_flock_shared, "exceeds 10s timeout"
exclude :test_grpowned_p, "work in progress"
exclude :test_join_ascii_incompatible, "needs investigation"
exclude :test_join_with_changed_separator, "needs investigation"
exclude :test_lchmod, "Fails when running with root privileges"
exclude :test_readlink_long_path, "needs investigation"
exclude :test_sgid, "needs investigation"
exclude :test_stat_grpowned_p, "work in progress"
exclude :test_sticky, "needs investigation"
exclude :test_suid, "needs investigation"
