exclude :test_accept_nonblock, "needs investigation"
exclude :test_addr, "needs investigation"
exclude :test_cloexec, "needs investigation"
exclude :test_dgram_pair, "needs investigation"
exclude :test_dgram_pair_sendrecvmsg_errno_set, "needs investigation"
exclude :test_epipe, "writing after shutdown(SHUT_WR) raises IOError, not Errno::EPIPE"
exclude :test_fd_passing, "close_on_exec? not implemented"
exclude :test_fd_passing_class_mode, "send_io fails with EPIPE"
exclude :test_fd_passing_race_condition, "needs investigation"
exclude :test_getpeereid, "needs investigation"
exclude :test_seqpacket_pair, "hangs (tested on macos M1)"
exclude :test_socket_pair_with_block, "needs investigation"
exclude :test_stream_pair, "hangs (tested on macos M1)"
exclude :test_unix_server_socket, "needs investigation"
exclude :test_unix_socket_pair_with_block, "needs investigation"
