exclude :test_completion_encoding, "needs investigation"
exclude :test_completion_proc, "needs investigation"
exclude :test_completion_proc_empty_result, "hangs waiting for input?"
exclude :test_input=, "needs investigation"
exclude :test_input_metachar, "needs investigation"
exclude :test_insert_text, "needs investigation"
exclude :test_line_buffer__point, "hangs waiting for input?"
exclude :test_modify_text_in_pre_input_hook, "needs investigation"
exclude :test_output=, "needs investigation"
exclude :test_pre_input_hook, "needs investigation"
exclude :test_readline, "hangs waiting for input?"
exclude :test_safe_level_4, "hangs waiting for input?"
exclude :test_some_characters_methods, "needs investigation"
