exclude :test_cloned_allows_setting_cvar, "needs investigation"
exclude :test_exivar_resize_with_compaction_stress, "depends on CRuby GC APIs"
exclude :test_global_variables, "requires dynamic listing of backref numbers for available groups"
exclude :test_setting_class_variable_on_module_through_inheritance, "work in progress"
exclude :test_singleton_class_included_class_variable, "work in progress"
exclude :test_special_constant_ivars, "work in progress"
exclude :test_svar_with_ifunc, "new isolation of proc frame captures, see https://github.com/jruby/jruby/issues/8726"
exclude :test_variable, "needs investigation"
