exclude :test_alias, "needs investigation"
exclude :test_attr, "needs investigation"
exclude :test_classpath, "needs investigation"
exclude :test_const_get_invalid_name, "UTF-16 invalid name is accepted as ok, unfinished in initial 2.6 work, #6161"
exclude :test_const_set_invalid_name, "UTF-16 invalid name is accepted as ok"
exclude :test_define_module_under_private_constant, "we don't evaluate colon2-like class opening via colon2 logic, can't tell if private are ok"
exclude :test_deprecate_nil_constant, "constants may recache after crossing JIT boundary (#6164)"
exclude :test_include_module_with_constants_does_not_invalidate_method_cache, "no RubyVM constant in JRuby"
exclude :test_initialize_copy_empty, "needs investigation"
exclude :test_invalid_attr, "needs investigation"
exclude :test_method_defined, "unfinished in initial 2.6 work, #6161"
exclude :test_method_defined_without_include_super, "unfinished in initial 2.6 work, #6161"
exclude :test_method_redefinition, "needs investigation"
exclude :test_private_constant_reopen, "needs investigation"
exclude :test_private_constant_with_no_args, "needs investigation"
exclude :test_protected_singleton_method, "needs investigation"
