exclude :test_addrinfo_new_unix, "needs investigation"
exclude :test_addrinfo_predicates_unix, "needs investigation"
exclude :test_basicsocket_send, "needs investigation"
exclude :test_connect, "needs investigation"
exclude :test_connect_from, "needs investigation"
exclude :test_connect_to, "needs investigation"
exclude :test_error_message, "unfinished in initial 2.6 work, #6161"
exclude :test_family_addrinfo, "needs investigation"
exclude :test_ipv6_address_predicates, "needs investigation"
exclude :test_ipv6_to_ipv4, "not implemented"
exclude :test_marshal, "needs investigation"
exclude :test_marshal_inet6, "needs investigation"
exclude :test_marshal_memory_leak, "no working assert_no_memory_leak method"
exclude :test_marshal_memory_leak, "work in progress"
exclude :test_marshal_unix, "needs investigation"
exclude :test_socket_accept, "needs investigation"
exclude :test_socket_accept_nonblock, "needs investigation"
exclude :test_socket_bind, "needs investigation"
exclude :test_socket_connect, "needs investigation"
exclude :test_socket_connect_nonblock, "needs investigation"
exclude :test_socket_getnameinfo, "needs investigation"
exclude :test_socket_recvfrom, "needs investigation"
exclude :test_socket_recvfrom_nonblock, "needs investigation"
exclude :test_socket_sysaccept, "needs investigation"
exclude :test_udpsocket_send, "needs investigation"
