exclude :test_basicobject, "work in progress"
exclude :test_callee_in_delegator_class, "needs investigation"
exclude :test_callee_in_simple_delegator, "needs investigation"
exclude :test_global_method_if_no_target, "https://bugs.ruby-lang.org/issues/9155"
exclude :test_systemcallerror_eq, "needs investigation"
