exclude :test_closed_outstream, "hangs"
exclude :test_completion_append_character, "work in progress"
exclude :test_completion_case_fold, "work in progress"
exclude :test_completion_encoding, "needs investigation"
exclude :test_completion_proc, "needs investigation"
exclude :test_completion_proc_empty_result, "hangs waiting for input"
exclude :test_completion_quote_character_after_completion, "work in progress"
exclude :test_completion_quote_character_completing_quoted_argument, "work in progress"
exclude :test_completion_quote_character_completing_unquoted_argument, "work in progress"
exclude :test_completion_with_completion_append_character, "hangs waiting for input"
exclude :test_delete_text, "work in progress"
exclude :test_editing_mode, "work in progress"
exclude :test_get_screen_size, "work in progress"
exclude :test_input=, "needs investigation"
exclude :test_input_metachar, "hangs waiting for input"
exclude :test_input_metachar_multibyte, "hangs waiting for input"
exclude :test_insert_text, "needs investigation"
exclude :test_interrupt_in_other_thread, "work in progress"
exclude :test_line_buffer__point, "hangs waiting for input"
exclude :test_modify_text_in_pre_input_hook, "needs investigation"
exclude :test_output=, "needs investigation"
exclude :test_point, "work in progress"
exclude :test_pre_input_hook, "needs investigation"
exclude :test_readline, "hangs waiting for input"
exclude :test_refresh_line, "work in progress"
exclude :test_safe_level_4, "hangs waiting for input"
exclude :test_setting_quoting_detection_proc, "work in progress"
exclude :test_simple_completion, "hangs waiting for input"
exclude :test_some_characters_methods, "needs investigation"
exclude :test_using_quoting_detection_proc, "work in progress"
exclude :test_using_quoting_detection_proc_with_multibyte_input, "work in progress"
exclude :test_without_tty, "work in progress"
