exclude :test_eval_ascii_incompatible, "needs investigation"
exclude :test_eval_location_binding, "unfinished in initial 2.6 work, #6161"
exclude :test_eval_location_fstring, "needs investigation"
exclude :test_file_encoding, "needs investigation"
exclude :test_fstring_instance_eval, "attempts to instance_eval a frozen String, which breaks because we create singleton class (https://github.com/jruby/jruby/issues/8638)"
exclude :test_return_in_eval_proc, "new LJE behavior or tests in Ruby 2.5"
