exclude :test_block_required_keyword, "needs investigation"
exclude :test_implicit_hash_conversion, "needs investigation"
exclude :test_p1, "needs investigation"
exclude :test_p3, "needs investigation"
exclude :test_p6, "needs investigation"
exclude :test_required_keyword_with_reserved, "needs investigation"
exclude :test_rest_keyrest, "needs investigation"
