exclude :test_array_empty?, "may be CRuby-specific, needs investigation"
exclude :test_array_hash, "may be CRuby-specific, needs investigation"
exclude :test_array_length, "may be CRuby-specific, needs investigation"
exclude :test_array_max, "may be CRuby-specific, needs investigation"
exclude :test_array_min, "may be CRuby-specific, needs investigation"
exclude :test_array_minus, "may be CRuby-specific, needs investigation"
exclude :test_array_plus, "may be CRuby-specific, needs investigation"
exclude :test_block_parameter_should_not_create_objects, "requires ObjectSpace count_objects"
exclude :test_c_func_with_sp_offset_under_tailcall, "may be CRuby-specific, needs investigation"
exclude :test_callinfo_unreachable_path, "depends on RubyVM, tests RubyVM::InstructionSequence"
exclude :test_clear_unreachable_keyword_args, "depends on RubyVM"
exclude :test_eqq, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_and, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_div, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_ge, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_gt, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_le, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_lt, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_minus, "needs investigation"
exclude :test_fixnum_mod, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_mul, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_or, "may be CRuby-specific, needs investigation"
exclude :test_fixnum_plus, "needs investigation"
exclude :test_float_div, "may be CRuby-specific, needs investigation"
exclude :test_float_ge, "may be CRuby-specific, needs investigation"
exclude :test_float_gt, "may be CRuby-specific, needs investigation"
exclude :test_float_le, "may be CRuby-specific, needs investigation"
exclude :test_float_lt, "may be CRuby-specific, needs investigation"
exclude :test_float_minus, "may be CRuby-specific, needs investigation"
exclude :test_float_mul, "may be CRuby-specific, needs investigation"
exclude :test_float_plus, "may be CRuby-specific, needs investigation"
exclude :test_hash_aref_with, "may be CRuby-specific, needs investigation"
exclude :test_hash_aset_with, "may be CRuby-specific, needs investigation"
exclude :test_hash_empty?, "may be CRuby-specific, needs investigation"
exclude :test_hash_length, "may be CRuby-specific, needs investigation"
exclude :test_objtostring, "may be CRuby-specific, needs investigation"
exclude :test_opt_case_dispatch, "depends on RubyVM"
exclude :test_opt_duparray_send_include_p, "may be CRuby-specific, needs investigation"
exclude :test_opt_new, "uses RubyVM"
exclude :test_opt_newarray_send_include_p, "may be CRuby-specific, needs investigation"
exclude :test_optimized_rescue, "may be CRuby-specific, needs investigation"
exclude :test_peephole_array_freeze, "may be CRuby-specific, needs investigation"
exclude :test_peephole_array_freeze_empty, "may be CRuby-specific, needs investigation"
exclude :test_peephole_dstr, "may be CRuby-specific, needs investigation"
exclude :test_peephole_hash_freeze, "may be CRuby-specific, needs investigation"
exclude :test_peephole_hash_freeze_empty, "may be CRuby-specific, needs investigation"
exclude :test_peephole_optimization_without_trace, "depends on RubyVM"
exclude :test_peephole_string_literal_range, "depends on RubyVM"
exclude :test_string_empty?, "may be CRuby-specific, needs investigation"
exclude :test_string_eq_neq, "may be CRuby-specific, needs investigation"
exclude :test_string_format, "may be CRuby-specific, needs investigation"
exclude :test_string_freeze, "frozen string literal should be a new object if String#freeze is redefined (#2156)"
exclude :test_string_freeze_block, "frozen string literal revert to a call if String#freeze is redefined (#2156)"
exclude :test_string_freeze_saves_memory, "depends on ObjectSpace#memsize_of"
exclude :test_string_length, "may be CRuby-specific, needs investigation"
exclude :test_string_ltlt, "may be CRuby-specific, needs investigation"
exclude :test_string_plus, "may be CRuby-specific, needs investigation"
exclude :test_string_size, "may be CRuby-specific, needs investigation"
exclude :test_string_succ, "may be CRuby-specific, needs investigation"
exclude :test_string_uminus, "frozen string literal revert to a call if String#-@ is redefined (#2156)"
exclude :test_tailcall, "needs investigation"
exclude :test_tailcall_and_post_arg, "may be CRuby-specific, needs investigation"
exclude :test_tailcall_condition_block, "depends on RubyVM"
exclude :test_tailcall_inhibited_by_block, "depends on RubyVM"
exclude :test_tailcall_inhibited_by_rescue, "depends on RubyVM"
exclude :test_tailcall_not_to_grow_stack, "may be CRuby-specific, needs investigation"
exclude :test_tailcall_symbol_block_arg, "depends on RubyVM"
exclude :test_tailcall_with_block, "needs investigation"
exclude :test_trace_optimized_methods, "may be CRuby-specific, needs investigation"