exclude :test_completion_proc_empty_result, "hangs waiting for input?"
exclude :test_completion_quote_character_after_completion, "hangs"
exclude :test_completion_quote_character_completing_quoted_argument, "hangs"
exclude :test_completion_quote_character_completing_unquoted_argument, "hangs"
exclude :test_without_tty, "work in progress"
