exclude :test_assignment_in_conditional, "line numbers don't match MRI"
exclude :test_backtrace_limit, "needs investigation"
exclude :test_chdir, "needs investigation"
exclude :test_copyright, "needs investigation"
exclude :test_debug, "needs investigation"
exclude :test_disable, "needs investigation"
exclude :test_dump_insns_with_rflag, "MRI-specific format"
exclude :test_dump_parsetree_with_rflag, "MRI-specific format"
exclude :test_dump_syntax_with_rflag, "MRI-specific format"
exclude :test_dump_yydebug_with_rflag, "MRI-specific format"
exclude :test_encoding, "needs investigation"
exclude :test_eval, "needs investigation"
exclude :test_flag_in_shebang, "unreliable with our bash script"
exclude :test_frozen_string_literal, "needs investigation"
exclude :test_frozen_string_literal_debug, "needs investigation #4303"
exclude :test_indentation_check, "hangs"
exclude :test_invalid_option, "needs investigation"
exclude :test_kanji, "needs investigation"
exclude :test_notfound, "needs investigation"
exclude :test_program_name, "needs investigation"
exclude :test_require, "needs investigation"
exclude :test_rubyopt, "needs investigation"
exclude :test_script_is_directory, "uses io/console in ways we don't support yet"
exclude :test_search, "passes independently but fails in suite"
exclude :test_segv_loaded_features, "needs investigation"
exclude :test_segv_setproctitle, "needs investigation"
exclude :test_segv_test, "needs investigation"
exclude :test_separator, "needs investigation"
exclude :test_sflag, "needs investigation"
exclude :test_shebang, "needs investigation"
exclude :test_unmatching_glob, "needs investigation"
exclude :test_unused_variable, "needs investigation"
exclude :test_usage, "expects a specific number of lines in -h output"
exclude :test_usage_long, "needs investigation"
exclude :test_warning, "needs investigation"
exclude :test_yydebug, "needs investigation"
