exclude :test_binmode_pipe, "work in progress"
exclude :test_cloexec, "needs investigation"
exclude :test_copy_stream_pipe_nonblock, "copy_stream does not block against a nonblocking stream (#2439)"
exclude :test_copy_stream_read_pipe, "needs investigation"
exclude :test_copy_stream_smaller, "needs investigation"
exclude :test_copy_stream_socket7, "uses fork"
exclude :test_cross_thread_close_stdio, "needs investigation"
exclude :test_dup_many, "needs investigation"
exclude :test_dup_timeout, "IO#timeout is not implemented yet (https://github.com/jruby/jruby/pull/8662)"
exclude :test_each_line, "needs investigation"
exclude :test_fcntl_dupfd, "needs investigation"
exclude :test_flush_in_finalizer1, "uses ObjectSpace"
exclude :test_flush_in_finalizer2, "uses ObjectSpace"
exclude :test_foreach, "fails to handle kwargs or raises wrong error"
exclude :test_gets_chomp_default_rs, "needs investigation"
exclude :test_puts_recursive_ary, "stack overflow in StringIO inspect"
exclude :test_race_gets_and_close, "racey test may not be valid since gets may proceed after stream is closed"
exclude :test_read_lock, "needs investigation"
exclude :test_read_nonblock_invalid_exception, "work in progress"
exclude :test_readlines_limit_0, "hangs"
exclude :test_readpartial_lock, "needs investigation"
exclude :test_readpartial_locktmp, "requires string locking we do not support"
exclude :test_recycled_fd_close, "IO#timeout is not implemented yet (https://github.com/jruby/jruby/pull/8662)"
exclude :test_reinitialize, "needs investigation"
exclude :test_reopen_encoding_from_io, "needs investigation"
exclude :test_reopen_opt, "needs investigation"
exclude :test_s_readlines, "needs investigation"
exclude :test_select_exceptfds, "hangs, and Java select does not really support erroring FDs"
exclude :test_select_memory_leak, "no working assert_no_memory_leak method"
exclude :test_set_lineno, "needs investigation"
exclude :test_set_stdout, "needs investigation"
exclude :test_std_fileno, "passes in isolation; some other test is causing STDIN to get a different fd"
exclude :test_stdout_to_closed_pipe, "work in progress"
exclude :test_sysread_locktmp, "needs investigation"
exclude :test_sysread_locktmp, "requires string locking we do not support"
exclude :test_ungetbyte_with_seek, "needs investigation"
exclude :test_ungetc_with_seek, "needs investigation"
exclude :test_write_nonblock_invalid_exception, "work in progress"
