exclude :test_anonymous_class_name, "needs investigation"
exclude :test_argf_memsize, "uses ObjectSpace.memsize_of"
exclude :test_count_imemo_objects, "needs investigation"
exclude :test_count_objects_size, "needs investigation"
exclude :test_count_objects_size_with_hash, "needs investigation"
exclude :test_count_objects_size_with_wrong_type, "currently unsupported"
exclude :test_count_symbols, "needs investigation"
exclude :test_count_tdata_objects, "needs investigation"
exclude :test_dump_addresses_match_dump_all_addresses, "dumping is largely a CRuby-specific feature"
exclude :test_dump_all, "dumping is largely a CRuby-specific feature"
exclude :test_dump_all_full, "dumping is largely a CRuby-specific feature"
exclude :test_dump_all_single_generation, "dumping is largely a CRuby-specific feature"
exclude :test_dump_array, "dumping is largely a CRuby-specific feature"
exclude :test_dump_callinfo_includes_mid, "dumping is largely a CRuby-specific feature"
exclude :test_dump_class_addresses_match_dump_all_addresses, "dumping is largely a CRuby-specific feature"
exclude :test_dump_control_char, "dumping is largely a CRuby-specific feature"
exclude :test_dump_dynamic_symbol, "dumping is largely a CRuby-specific feature"
exclude :test_dump_escapes_method_name, "dumping is largely a CRuby-specific feature"
exclude :test_dump_flags, "dumping is largely a CRuby-specific feature"
exclude :test_dump_includes_imemo_type, "dumping is largely a CRuby-specific feature"
exclude :test_dump_includes_slot_size, "dumping is largely a CRuby-specific feature"
exclude :test_dump_not_too_complex_shape, "dumping is largely a CRuby-specific feature"
exclude :test_dump_object, "dumping is largely a CRuby-specific feature"
exclude :test_dump_objects_dumps_page_slot_sizes, "dumping is largely a CRuby-specific feature"
exclude :test_dump_reference_addresses_match_dump_all_addresses, "dumping is largely a CRuby-specific feature"
exclude :test_dump_shapes, "dumping is largely a CRuby-specific feature"
exclude :test_dump_singleton_class, "dumping is largely a CRuby-specific feature"
exclude :test_dump_special_consts, "dumping is largely a CRuby-specific feature"
exclude :test_dump_special_floats, "dumping is largely a CRuby-specific feature"
exclude :test_dump_string_coderange, "dumping is largely a CRuby-specific feature"
exclude :test_dump_to_default, "dumping is largely a CRuby-specific feature"
exclude :test_dump_to_io, "dumping is largely a CRuby-specific feature"
exclude :test_dump_uninitialized_file, "dumping is largely a CRuby-specific feature"
exclude :test_escape_class_name, "needs investigation"
exclude :test_internal_class_of, "does not seem to have objectspace enabled when run"
exclude :test_internal_class_of_on_ast, "we do not support RubyVM::AST"
exclude :test_internal_super_of, "currently unsupported"
exclude :test_load_allocation_path_compile_file, "needs investigation"
exclude :test_load_allocation_path_load, "needs investigation"
exclude :test_memsize_of, "uses ObjectSpace.memsize_of"
exclude :test_memsize_of_all, "uses ObjectSpace.memsize_of"
exclude :test_memsize_of_iseq, "uses ObjectSpace.memsize_of, no iseq support"
exclude :test_memsize_of_root_shared_string, "uses ObjectSpace.memsize_of"
exclude :test_name_error_message, "needs investigation"
exclude :test_objspace_trace, "currently unsupported"
exclude :test_reachable_objects_during_iteration, "needs investigation"
exclude :test_reachable_objects_from, "needs investigation"
exclude :test_reachable_objects_from_root, "needs investigation"
exclude :test_reachable_objects_size, "uses ObjectSpace.memsize_of"
exclude :test_trace_object_allocations, "no support on JVM for live allocation tracking"
exclude :test_trace_object_allocations_compaction, "no support on JVM for live allocation tracking"
exclude :test_trace_object_allocations_gc_stress, "no support on JVM for live allocation tracking"
exclude :test_trace_object_allocations_start_stop_clear, "no support on JVM for live allocation tracking"
exclude :test_trace_object_allocations_stop_first, "no support on JVM for live allocation tracking"
exclude :test_utf8_method_names, "needs investigation"
