exclude :test_AREF_fstring_key_default_proc, "Depends on MRI-specific ObjectSpace.count_objects"
exclude :test_compare_by_identy_memory_leak, "no working assert_no_memory_leak method"
exclude :test_fetch_error, "needs investigation"
exclude :test_inspect, "not matching special symbols requiring hashrocket vs colon"
exclude :test_st_literal_memory_leak, "no working assert_no_memory_leak method"
