exclude :test_bom_16le, "needs investigation"
exclude :test_each_byte_extended_file, "needs investigation"
exclude :test_each_char_extended_file, "needs investigation"
exclude :test_getbyte_extended_file , "needs investigation"
exclude :test_getc_extended_file , "needs investigation"
exclude :test_gets_extended_file , "needs investigation"
exclude :test_gets_para_extended_file , "needs investigation"
exclude :test_read_all_extended_file , "needs investigation"
exclude :test_stat , "birthtime does not match MRI behavior (#2152)"
exclude :test_truncate_wbuf, "fails on Linux"
