exclude :test_beginendblock, "needs investigation"
exclude :test_begininclass, "needs investigation"
exclude :test_begininmethod, "needs investigation"
exclude :test_callcc_at_exit, "Continuations are not supported"
exclude :test_internal_errinfo_at_exit, "no fork"
exclude :test_propagate_signaled, "needs investigation"
exclude :test_raise_in_at_exit, "need to run multiple -e as separate top-level scripts (#3674)"
