exclude :test_cause_exception_in_cause_message, "we don't dynamically call #to_s when printing exceptions"
exclude :test_control_in_message, "encoding challenges with exception messages"
exclude :test_errinfo_encoding_in_debug, "encoding challenges with exception messages"
exclude :test_exception_in_ensure_with_next, "uses RubyVM"
exclude :test_kernel_warn_uplevel, "we don't implement warn(uplevel:)"
exclude :test_machine_stackoverflow, "expects Ruby SystemStackError, but we only propagate java.lang.StackOverflowError"
exclude :test_machine_stackoverflow_by_define_method, "expects Ruby SystemStackError, but we only propagate java.lang.StackOverflowError"
exclude :test_multibyte_and_newline, "encoding challenges with exception messages"
exclude :test_output_string_encoding, "encoding challenges with exception messages"
exclude :test_redefined_backtrace, "we don't dynamically call #backtrace"
exclude :test_stackoverflow, "expects Ruby SystemStackError, but we only propagate java.lang.StackOverflowError"
exclude :test_syntax_error_detailed_message, "passes with Prism parser"
exclude :test_too_many_args_in_eval, "JRuby has much higher limits for passing arguments in the interpreter"
exclude :test_wrong_backtrace, "we don't dynamically call #backtrace"
