exclude :test_close_bang_does_not_unlink_if_already_unlinked, "needs investigation"
exclude :test_close_bang_works, "needs investigation"
exclude :test_close_with_unlink_now_true_does_not_unlink_if_already_unlinked, "needs investigation"
exclude :test_close_with_unlink_now_true_works, "needs investigation"
exclude :test_finalizer_does_not_unlink_if_already_unlinked, "needs investigation"
exclude :test_tempfile_finalizer_does_not_run_if_unlinked, "needs investigation"
exclude :test_tempfile_is_unlinked_when_ruby_exits, "needs investigation"
