exclude :test_attr_source_location, "needs investigation"
exclude :test_binding_error_unless_ruby_frame, "appears to rely on CRuby framing logic"
exclude :test_dup_clone, "needs investigation"
exclude :test_hash_does_not_change_after_compaction, "needs investigation"
exclude :test_hash_equal, "needs investigation"
exclude :test_parameters, "needs investigation"
exclude :test_proc_args_single_kw_no_autosplat, "needs investigation"
exclude :test_proc_args_single_kwsplat_no_autosplat, "needs investigation"
exclude :test_proc_autosplat, "work in progress"
exclude :test_proc_autosplat_with_multiple_args_with_ruby2_keywords_splat_bug_19759, "needs investigation"
