exclude :test_ancestors, "work in progress"
exclude :test_import_methods, "work in progress"
exclude :test_inlinecache, "needs investigation"
exclude :test_prepend_refined_module, "work in progress"
exclude :test_refine_frozen_class, "work in progress"
exclude :test_refine_prepended_class, "markers not being applied properly to prepended module"
exclude :test_refined_method_alias_warning, "work in progress"
exclude :test_refined_protected_methods, "needs investigation"
exclude :test_super_to_module, "issues finding proper super hierarchy, perhaps related to #5585"
exclude :test_to_proc, "not implemented, jruby/jruby#6161"
exclude :test_unbound_refine_method, "work in progress"
exclude :test_unbound_refine_method, "work in progress"
exclude :test_undef_original_method, "flaw in how we represent undef methods; they look the same as never-defined"
exclude :test_undef_prepended_method, "flaw in how we represent undef methods; they look the same as never-defined"
exclude :test_used_modules, "needs investigation"
exclude :test_used_refinements, "needs investigation"
