exclude :test_div_gh220, "needs investigation"
exclude :test_exception_overflow, "runs forever"
exclude :test_limit, "needs investigation"
exclude :test_new_subclass, "work in progress"
exclude :test_round_up, "needs investigation"
exclude :test_s_new, "work in progress"
exclude :test_thread_local_mode, "needs investigation"
