exclude :test_count_objects, "unsupported feature"
exclude :test_exception_in_finalizer, "work in progress"
exclude :test_finalizer, "needs investigation"
exclude :test_finalizer_thread_raise, "no without_gc support"
exclude :test_id2ref_invalid_argument, "work in progress"
exclude :test_id2ref_invalid_symbol_id, "depends on CRuby-specific layout of symbols and their IDs"
