exclude :test_bind, "needs investigation"
exclude :test_bind_addrinuse, "needs investigation"
exclude :test_bind_no_memory_leak, "no working assert_no_memory_leak method"
exclude :test_bind_no_memory_leak, "work in progress"
exclude :test_connect_no_memory_leak, "no working assert_no_memory_leak method"
exclude :test_connect_no_memory_leak, "work in progress"
exclude :test_inspect, "missing socket information"
exclude :test_send_no_memory_leak, "no working assert_no_memory_leak method"
exclude :test_send_no_memory_leak, "work in progress"
exclude :test_send_too_long, "needs investigation"
