exclude :test_bug_21210, "depends on CRuby GC APIs"
exclude :test_copy_null_destination, "no support for null buffer"
exclude :test_copy_null_source, "no support for null buffer"
exclude :test_copy_overlapped_bwd, "needs investigation"
exclude :test_file_mapped, "open files can't be memory-mapped due to jnr-enxio (https://github.com/jruby/jruby/issues/8714)"
exclude :test_file_mapped_size_just_enough, "open files can't be memory-mapped due to jnr-enxio (https://github.com/jruby/jruby/issues/8714)"
exclude :test_file_mapped_with_size, "open files can't be memory-mapped due to jnr-enxio (https://github.com/jruby/jruby/issues/8714)"
exclude :test_file_mapped_offset_too_large, "open files can't be memory-mapped due to jnr-enxio (https://github.com/jruby/jruby/issues/8714)"
exclude :test_file_mapped_negative_offset, "open files can't be memory-mapped due to jnr-enxio (https://github.com/jruby/jruby/issues/8714)"
exclude :test_file_mapped_size_too_large, "open files can't be memory-mapped due to jnr-enxio (https://github.com/jruby/jruby/issues/8714)"
exclude :test_file_mapped_zero_size, "open files can't be memory-mapped due to jnr-enxio (https://github.com/jruby/jruby/issues/8714)"
exclude :test_private, "open files can't be memory-mapped due to jnr-enxio (https://github.com/jruby/jruby/issues/8714)"
exclude :test_read_with_length_and_offset, "read of zero is supposed to read as much as it can"
exclude :test_resize_zero_external, "missing AccessError"
exclude :test_set_string_null_destination, "needs investigation"
exclude :test_set_string_overlapped_bwd, "needs investigation"
exclude :test_string_mapped_buffer_locked, "missing RuntimeError"
exclude :test_transfer_in_block, "missing AccessError"
