exclude :test_initialize_failure, "needs investigation"
exclude :test_initialize_fast_fallback_is_false, "needs investigation"
exclude :test_initialize_resolv_timeout, "work in progress"
exclude :test_initialize_resolv_timeout_with_connection_failure, "needs investigation"
exclude :test_initialize_v4_hostname_resolved_earlier, "needs investigation"
exclude :test_initialize_v6_hostname_resolution_failed_and_v4_hostname_resolution_is_success, "hangs on macos M1"
exclude :test_initialize_v6_hostname_resolved_earlier, "hangs on macos M1"
exclude :test_initialize_v6_hostname_resolved_earlier_and_v6_server_is_not_listening, "needs investigation"
exclude :test_initialize_v6_hostname_resolved_in_resolution_delay, "hangs on macos M1"
exclude :test_initialize_v6_hostname_resolved_later_and_v6_server_is_not_listening, "needs investigation"
exclude :test_initialize_with_connection_failure_after_hostname_resolution_failure, "needs investigation"
exclude :test_initialize_with_hostname_resolution_failure_after_connection_failure, "needs investigation"
exclude :test_inspect, "missing socket information"
exclude :test_recvfrom, "no addrinfo returned"
