exclude :test_from_cp50221, "needs investigation"
exclude :test_gb18030, "perhaps a bug in pack wrt encoded text"
exclude :test_gb2312, "needs investigation"
exclude :'test_pseudo_encoding_inspect(UTF-16)', "needs investigation"
exclude :'test_pseudo_encoding_inspect(UTF-32)', "needs investigation"
exclude :test_to_cp50221, "needs investigation"
exclude :test_unicode_public_review_issue_121, "broken via charset replacement"
exclude :test_utf8_mac, "needs investigation"
exclude :test_utf_32_bom, "needs investigation"
