exclude :test_anonymous_class_name, "needs investigation"
exclude :test_argf_memsize, "currently unsupported"
exclude :test_count_imemo_objects, "needs investigation"
exclude :test_count_objects_size, "needs investigation"
exclude :test_count_objects_size_with_hash, "needs investigation"
exclude :test_count_objects_size_with_wrong_type, "currently unsupported"
exclude :test_count_symbols, "needs investigation"
exclude :test_count_tdata_objects, "needs investigation"
exclude :test_dump_addresses_match_dump_all_addresses, "currently unsupported"
exclude :test_dump_all, "currently unsupported"
exclude :test_dump_all_full, "currently unsupported"
exclude :test_dump_all_single_generation, "currently unsupported"
exclude :test_dump_array, "currently unsupported"
exclude :test_dump_class_addresses_match_dump_all_addresses, "currently unsupported"
exclude :test_dump_control_char, "needs investigation"
exclude :test_dump_dynamic_symbol, "needs investigation"
exclude :test_dump_escapes_method_name, "needs investigation"
exclude :test_dump_flags, "needs investigation"
exclude :test_dump_includes_imemo_type, "currently unsupported"
exclude :test_dump_includes_slot_size, "currently unsupported"
exclude :test_dump_not_too_complex_shape, "work in progress"
exclude :test_dump_object, "work in progress"
exclude :test_dump_reference_addresses_match_dump_all_addresses, "work in progress"
exclude :test_dump_shapes, "needs investigation"
exclude :test_dump_singleton_class, "needs investigation"
exclude :test_dump_special_consts, "needs investigation"
exclude :test_dump_special_floats, "needs investigation"
exclude :test_dump_string_coderange, "needs investigation"
exclude :test_dump_to_default, "needs investigation"
exclude :test_dump_to_io, "needs investigation"
exclude :test_dump_uninitialized_file, "work in progress"
exclude :test_internal_class_of, "needs investigation"
exclude :test_internal_class_of_on_ast, "needs investigation"
exclude :test_internal_class_of_on_ast, "we do not support RubyVM::AST"
exclude :test_internal_super_of, "currently unsupported"
exclude :test_load_allocation_path_compile_file, "needs investigation"
exclude :test_load_allocation_path_load, "needs investigation"
exclude :test_memsize_of, "needs investigation"
exclude :test_memsize_of_all, "currently unsupported"
exclude :test_memsize_of_iseq, "needs investigation"
exclude :test_memsize_of_iseq, "we don't have iseq"
exclude :test_memsize_of_root_shared_string, "needs investigation"
exclude :test_name_error_message, "needs investigation"
exclude :test_objspace_trace, "currently unsupported"
exclude :test_reachable_objects_during_iteration, "needs investigation"
exclude :test_reachable_objects_from, "needs investigation"
exclude :test_reachable_objects_from_root, "needs investigation"
exclude :test_reachable_objects_size, "needs investigation"
exclude :test_trace_object_allocations, "needs investigation"
exclude :test_trace_object_allocations_gc_stress, "needs investigation"
exclude :test_trace_object_allocations_start_stop_clear, "needs investigation"
exclude :test_trace_object_allocations_stop_first, "needs investigation"
exclude :test_utf8_method_names, "needs investigation"
