exclude :test_initialize_failure, "needs investigation"
exclude :test_initialize_resolv_timeout, "work in progress"
exclude :test_inspect, "missing socket information"
exclude :test_recvfrom, "no addrinfo returned"
exclude :test_initialize_v6_hostname_resolved_in_resolution_delay, "hangs on macos M1"
exclude :test_initialize_v6_hostname_resolution_failed_and_v4_hostname_resolution_is_success, "hangs on macos M1"
exclude :test_initialize_v6_hostname_resolved_earlier, "hangs on macos M1"
