exclude :"test_strip_bom:UTF-16LE", "work in progress"
exclude :test_error_nonascii, "needs investigation"
exclude :test_getc_newlineconv_invalid, "needs investigation"
exclude :test_inspect_nonascii, "needs investigation"
exclude :test_open_pipe_r_enc2, "needs investigation"
exclude :test_puts_widechar, "needs investigation"
exclude :test_set_encoding_unsupported, "needs investigation"
exclude :test_undef_r, "needs investigation"
exclude :test_undef_w_stateful, "needs investigation"
exclude :test_undef_w_stateless, "needs investigation"
