exclude :test___dir__, "needs investigation"
exclude :test_alias_owner, "needs investigation"
exclude :test_body, "needs investigation"
exclude :test_callee, "needs investigation"
exclude :test_clone, "needs investigation"
exclude :test_define_method_visibility, "needs investigation"
exclude :test_define_singleton_method, "needs investigation"
exclude :test_eq, "needs investigation"
exclude :test_hash, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_singleton_method, "needs investigation"
exclude :test_super_in_proc_from_define_method, "needs investigation"
exclude :test_super_method_removed, "finds super method when super method has been undef (#2155)"
exclude :test_visibility, "fails in compiler"
