exclude :test_initialize_frozen, "precision issue?"
exclude :test_marshal_load_frozen, "precision issue?"
exclude :test_marshal_load_insecure, "precision issue?"
exclude :test_random_range, "precision issue?"
exclude :test_rand_reseed_on_fork, "precision issue?"
