exclude :test_cclass_X, "Unicode 9.0 update in 2.4 (#4731)"
exclude :test_char_class, "needs investigation"
exclude :test_dup_warn, "needs investigation"
exclude :test_equal, "needs investigation"
exclude :test_initialize, "needs investigation"
exclude :test_invalid_escape_error, "needs investigation"
exclude :test_invalid_fragment, "needs investigation"
exclude :test_match_without_regexp, "matches non-unicode with exception message using regexp, but our messages are always unicode"
exclude :test_named_capture_nonascii, "needs investigation"
exclude :test_once_multithread, "fails intermittently"
exclude :test_options_in_look_behind, "needs investigation"
exclude :test_quote, "Likely unicode 9 update-related (#4731)"
exclude :test_raw_hyphen_and_tk_char_type_after_range, "needs investigation"
exclude :test_regsub_K, "needs investigation"
exclude :test_source, "needs investigation"
exclude :test_source_unescaped, "needs investigation"
exclude :test_taint, "needs investigation"
exclude :test_to_s, "needs investigation"
exclude :test_unescape, "needs investigation"
