exclude :test_any_hash_fixable, "launches many subprocesses and does not test anything useful on JRuby"
exclude :test_compare_by_id_memory_leak, "no working assert_no_memory_leak method"
exclude :test_exception_in_rehash_memory_leak, "no working assert_no_memory_leak method"
exclude :test_float_hash_random, "launches many subprocesses"
exclude :test_integer_hash_random, "JRuby does not randomize hash calculation for integer keys, see https://bugs.ruby-lang.org/issues/13002"
exclude :test_rehash_memory_leak, "no working assert_no_memory_leak method"
exclude :test_replace_memory_leak, "no working assert_no_memory_leak method"
exclude :test_st_literal_memory_leak, "no working assert_no_memory_leak method"
exclude :test_string_hash_random, "launches many subprocesses"
exclude :test_symbol_hash_random, "launches many subprocesses"
