exclude :test_AREF, "work in progress"
exclude :test_captures, "work in progress"
exclude :test_get_byte, "work in progress"
exclude :test_getch, "work in progress"
exclude :test_matched, "work in progress"
exclude :test_post_match, "work in progress"
exclude :test_pre_match, "work in progress"
exclude :test_values_at, "work in progress"
