exclude :test_accumulate_dst1, "needs investigation"
exclude :test_accumulate_dst2, "needs investigation"
exclude :test_convpath, "needs investigation"
exclude :test_default_external, "needs investigation"
exclude :test_invalid_utf16be, "needs investigation"
exclude :test_invalid_utf16le, "needs investigation"
exclude :test_invalid_utf32be, "needs investigation"
exclude :test_invalid_utf32le, "needs investigation"
exclude :test_iso2022jp_decode, "needs investigation"
exclude :test_iso2022jp_encode, "needs investigation"
exclude :test_iso2022jp_invalid_replace, "needs investigation"
exclude :test_newline_option, "unknown encoding name -"
exclude :test_noconv_insert_output, "needs investigation"
exclude :test_s_new_convpath, "needs investigation"
