exclude :test_include_into_refinement, "zsuper in module issue #5585"
exclude :test_prepend_into_refinement, "zsuper in module issue #5585"
exclude :test_refine_prepended_class, "markers not being applied properly to prepended module"
exclude :test_refine_with_prepend, "markers not being applied properly to target that has a prepend"
exclude :test_send_should_use_refinements, "todo"
exclude :test_super_to_module, "issues finding proper super hierarchy, perhaps related to #5585"
exclude :test_undef_original_method, "flaw in how we represent undef methods; they look the same as never-defined"
exclude :test_undef_prepended_method, "flaw in how we represent undef methods; they look the same as never-defined"
exclude :test_unused_refinement_for_module, "original method resolution needs to find proper super class, see #5585"
