exclude :test_error, "work in progress"
exclude :test_fatal_in_fiber, "work in progress"
exclude :test_fiber_transfer_segv, "wonky subprocess launching in test"
exclude :test_gc_root_fiber, "wonky subprocess launching in test"
exclude :test_many_fibers, "spins up too many fibers at once (10000)"
exclude :test_many_fibers_with_threads, "takes a very long time to run"
exclude :test_no_valid_cfp, "expects error where we and 2.0.0 do not present one"
exclude :test_prohibit_transfer_to_resuming_fiber, "hangs"
exclude :test_prohibit_transfer_to_yielding_fiber, "hangs"
exclude :test_resume_root_fiber, "why can main thread fiber resume itself but non-main thread cannot?"
exclude :test_separate_lastmatch, "work in progress"
exclude :test_terminate_transferred_fiber, "work in progress"
exclude :test_to_s, "work in progress"
