exclude :test_bad_initialize_copy, "needs investigation"
exclude :test_convert_type, "needs investigation"
exclude :test_freeze_immediate, "needs investigation"
exclude :test_implicit_respond_to, "encoding mismatch on symbol"
exclude :test_implicit_respond_to_arity_3, "encoding mismatch on symbol"
exclude :test_inspect, "encoding mismatch on symbol"
exclude :test_instance_variable_defined, "encoding mismatch on symbol"
exclude :test_instance_variable_get, "encoding mismatch on symbol"
exclude :test_instance_variable_set, "encoding mismatch on symbol"
exclude :test_method_missing, "needs investigation"
exclude :test_redef_method_missing, "needs investigation"
exclude :test_redefine_method_under_verbose, "needs investigation"
exclude :test_redefine_method_which_may_case_serious_problem, "needs investigation"
exclude :test_remove_instance_variable, "needs investigation"
exclude :test_remove_method, "needs investigation"
exclude :test_respond_to_missing, "needs investigation"
exclude :test_superclass_method, "needs investigation"
exclude :test_to_s, "needs investigation"
exclude :test_type_error_message, "needs investigation"
exclude :test_untrusted, "needs investigation"
