exclude :test_count_objects, "we don't run this suite with ObjectSpace on"
exclude :test_each_object, "we don't run this suite with ObjectSpace on"
exclude :test_each_object_enumerator, "we don't run this suite with ObjectSpace on"
exclude :test_each_object_no_gabage, "we don't run this suite with ObjectSpace on"
exclude :test_each_object_no_garbage, "work in progress"
exclude :test_exception_in_finalizer, "work in progress"
exclude :test_finalizer, "we don't run this suite with ObjectSpace on"
exclude :test_id2ref_18, "we don't run this suite with ObjectSpace on"
exclude :test_id2ref_28, "we don't run this suite with ObjectSpace on"
exclude :test_id2ref_29, "we don't run this suite with ObjectSpace on"
exclude :test_id2ref_30, "we don't run this suite with ObjectSpace on"
exclude :test_id2ref_31, "we don't run this suite with ObjectSpace on"
exclude :test_id2ref_32, "we don't run this suite with ObjectSpace on"
exclude :test_id2ref_33, "we don't run this suite with ObjectSpace on"
exclude :test_id2ref_invalid_argument, "work in progress"
