exclude :test_argf, "needs investigation"
exclude :test_bytes, "needs investigation - deprecated not matched"
exclude :test_chars, "needs investigation - deprecated not matched"
exclude :test_close_replace, "needs investigation"
exclude :test_codepoints, "needs investigation"
exclude :test_each_line_limit_0, "needs investigation"
exclude :test_encoding, "needs investigation"
exclude :test_eof, "needs investigation"
exclude :test_filename2, "needs investigation"
exclude :test_inplace, "needs investigation"
exclude :test_inplace2, "needs investigation"
exclude :test_inplace3, "needs investigation"
exclude :test_inplace_dup, "needs investigation"
exclude :test_inplace_no_backup, "needs investigation"
exclude :test_inplace_rename_impossible, "needs investigation"
exclude :test_inplace_stdin, "needs investigation"
exclude :test_inplace_stdin2, "needs investigation"
exclude :test_lineno, "needs investigation"
exclude :test_lineno2, "needs investigation"
exclude :test_lineno3, "needs investigation"
exclude :test_lines, "needs investigation"
exclude :test_readlines_limit_0, "HANGS"
exclude :test_skip, "needs investigation"
exclude :test_skip_in_each_char, "needs investigation"
exclude :test_skip_in_each_codepoint, "needs investigation"
exclude :test_to_io, "needs investigation"
exclude :test_unreadable, "needs investigation"
