exclude :test_queue_clear_return_value, "needs investigation"
exclude :test_queue_push_return_value, "needs investigation"
exclude :test_sized_queue_assign_max, "needs investigation"
exclude :test_sized_queue_clear_return_value, "needs investigation"
exclude :test_sized_queue_initialize, "needs investigation"
exclude :test_sized_queue_push_interrupt, "needs investigation"
exclude :test_sized_queue_push_return_value, "needs investigation"
exclude :test_thr_kill, "needs investigation"