exclude :test_copied_ivar_memory_leak,                        "uses MRI-specific code in memory_status.rb"
exclude :test_max_shape_variation_with_performance_warnings,  "CRuby-specific performance warning about too many object shapes"
exclude :test_methods_prepend_singleton, "work in progress"
exclude :test_redefine_method_under_verbose,                  "needs warning message"
exclude :test_redefine_method_which_may_case_serious_problem, "needs warning message"
exclude :test_remove_instance_variable_re_embed,  "CRuby-specific ObjectSpace.dump for inspecting internal object details"
exclude :test_remove_method, "works behaviorally but error message with multibyte name gets mangled"
exclude :test_singleton_methods, "work in progress"
exclude :test_type_error_message,                             "needs investigation"
