exclude :test_define_method_toplevel, "needs investigation"
exclude :test_eval_ascii_incompatible, "needs investigation"
exclude :test_eval_with_toplevel_binding, "needs investigation"
exclude :test_file_encoding, "needs investigation"
exclude :test_instance_eval_method, "needs investigation"
