exclude :test_tracer_by_add_filter_with_block, "work in progress"
exclude :test_tracer_by_add_filter_with_proc, "work in progress"
exclude :test_tracer_by_set_get_line_procs_with_block, "work in progress"
exclude :test_tracer_by_set_get_line_procs_with_proc, "work in progress"
exclude :test_tracer_with_option_r, "minor differences in output at toplevel"
exclude :test_tracer_with_option_r_without_gems, "minor differences in output at toplevel"
