exclude :test_bug_18343, "work in progress"
exclude :test_format_string_modified, "needs investigation"
exclude :test_integer_endian, "needs investigation"
exclude :test_integer_endian_explicit, "needs investigation"
exclude :test_invalid_warning, "needs investigation"
exclude :test_length_too_big, "needs investigation"
exclude :test_pack_P, "needs investigation"
exclude :test_pack_garbage, "needs investigation"
exclude :test_pack_infection, "needs original obj passed into bowels of unpack impl"
exclude :test_pack_p, "needs investigation"
exclude :test_pack_resize, "needs investigation"
exclude :test_pack_unpack_M, "needs investigation"
exclude :test_pack_unpack_P2, "needs investigation"
exclude :test_pack_unpack_atmark, "errors differently in JRuby but does not overrun buffer (https://hackerone.com/reports/298246)"
exclude :test_pack_unpack_bB, "needs investigation"
exclude :test_pack_unpack_hH, "needs investigation"
exclude :test_pack_unpack_jJ, "pointer packing, may not be relevant or useful in JRuby"
exclude :test_pack_unpack_qQ, "needs investigation"
exclude :test_pack_unpack_u, "needs investigation"
exclude :test_short_with_block, "needs investigation"
exclude :test_unpack_garbage, "needs investigation"
