exclude :test_call, "needs investigation"
exclude :test_check_localvars, "needs investigation"
exclude :test_create, "Continuations are not supported"
exclude :test_error, "Continuations are not supported"
exclude :test_tracing_with_set_trace_func, "needs investigation"
exclude :test_tracing_with_thread_set_trace_func, "needs investigation"
