exclude :test_call_ifunc_iseq_large_array_splat_fail, "tests internal CRuby functions"
exclude :test_call_rb_call_iseq_large_array_splat_pass, "tests internal CRuby functions"
exclude :test_call_rb_call_bmethod_large_array_splat_fail, "tests internal CRuby functions"
exclude :test_call_ifunc_iseq_large_array_splat_pass, "tests internal CRuby functions"
exclude :test_call_rb_call_iseq_large_array_splat_fail, "tests internal CRuby functions"
exclude :test_call_rb_call_bmethod_large_array_splat_pass, "tests internal CRuby functions"
