exclude :test_define_method, "needs investigation"
exclude :test_double_include, "needs investigation"
exclude :test_double_include2, "needs investigation"
exclude :test_missing_super_in_module_unbound_method, "needs investigation"
exclude :test_super_in_BEGIN, "problems with non-MRI check_syntax, test supers up wrong method"
exclude :test_super_in_instance_eval, "needs investigation"
exclude :test_super_in_instance_eval_with_define_method, "needs investigation"
exclude :test_super_in_module_unbound_method, "needs investigation"
exclude :test_super_in_orphan_block_with_instance_eval, "needs investigation"
exclude :test_overlaid, "broken in IR"
