exclude :test_attr, "needs investigation"
exclude :test_bug17590, "work in progress"
exclude :test_class_variable_in_dup_class, "work in progress"
exclude :test_classpath, "needs investigation"
exclude :test_complemented_method_entry_memory_leak, "no working assert_no_memory_leak method"
exclude :test_const_get_invalid_name, "UTF-16 invalid name is accepted as ok, unfinished in initial 2.6 work, #6161"
exclude :test_const_set_invalid_name, "UTF-16 invalid name is accepted as ok"
exclude :test_constant_access_from_method_in_cloned_module, "work in progress"
exclude :test_define_module_under_private_constant, "we don't evaluate colon2-like class opening via colon2 logic, can't tell if private are ok"
exclude :test_deprecate_constant, "work in progress"
exclude :test_deprecate_nil_constant, "constants may recache after crossing JIT boundary (#6164)"
exclude :test_iclass_memory_leak, "no working assert_no_memory_leak method"
exclude :test_include_module_with_constants_does_not_invalidate_method_cache, "no RubyVM constant in JRuby"
exclude :test_include_with_prepend, "work in progress"
exclude :test_initialize_copy, "work in progress"
exclude :test_initialize_copy_empty, "needs investigation"
exclude :test_invalid_attr, "needs investigation"
exclude :test_method_redefinition, "needs investigation"
exclude :test_module_clone_memory_leak, "no working assert_no_memory_leak method"
exclude :test_module_function_inside_method, "work in progress"
exclude :test_nested_defined, "needs investigation"
exclude :test_nested_defined, "work in progress"
exclude :test_nested_get, "needs investigation"
exclude :test_prepend_constant_lookup, "work in progress"
exclude :test_prepend_works_with_duped_classes, "work in progress"
exclude :test_prepended_module_with_super_and_alias, "work in progress"
exclude :test_private_constant_reopen, "needs investigation"
exclude :test_private_constant_with_no_args, "needs investigation"
exclude :test_protected_singleton_method, "needs investigation"
exclude :test_redefinition_mismatch, "work in progress"
