exclude :test_AREF_invalid_encoding, "needs investigation"
exclude :test_AREF_underflow, "needs investigation"
exclude :test_ASET, "expected behavior; JRuby can only do int range offsets into a string (integer -9223372036854775808 too small to convert to `int')"
exclude :test_byteindex, "needs investigation"
exclude :test_byterindex, "needs investigation"
exclude :test_crypt, "no working assert_no_memory_leak method"
exclude :test_delete_prefix_bang_broken_encoding, "needs investigation"
exclude :test_delete_prefix_broken_encoding, "needs investigation"
exclude :test_each_line_chomp, "needs investigation"
exclude :test_encode_fallback_not_string_memory_leak, "no working assert_no_memory_leak method"
exclude :test_encode_fallback_raise_memory_leak, "no working assert_no_memory_leak method"
exclude :test_encode_fallback_too_big_memory_leak, "no working assert_no_memory_leak method"
exclude :test_fs_setter, "needs investigation"
exclude :test_grapheme_clusters, "unfinished in initial 2.6 work, #6161"
exclude :test_grapheme_clusters_memory_leak, "no working assert_no_memory_leak method"
exclude :test_gsub_bang_gc_compact_stress, "GC is not configurable"
exclude :test_gsub_gc_compact_stress, "GC is not configurable"
exclude :test_hash, "needs investigation"
exclude :test_index, "needs investigation"
exclude :test_initialize_memory_leak, "no working assert_no_memory_leak method"
exclude :test_initialize_nofree_memory_leak, "no working assert_no_memory_leak method"
exclude :test_inspect_next_line, "needs investigation"
exclude :test_rindex, "needs investigation"
exclude :test_rstrip_bang, "needs investigation"
exclude :test_scan_gc_compact_stress, "GC is not configurable"
exclude :test_scan_segv, "requires ObjectSpace.each_object"
exclude :test_start_with?, "needs investigation"
exclude :test_start_with_timeout_memory_leak, "no working assert_no_memory_leak method"
exclude :test_string_interpolations_across_heaps_get_embedded, "uses internal GC constants"
exclude :test_sub_gc_compact_stress, "GC is not configurable"
exclude :test_sum_2, "needs investigation"
exclude :test_tr!, "needs investigation"
exclude :test_tr, "needs investigation"
exclude :test_tr_s!, "needs investigation"
exclude :test_tr_s, "needs investigation"
exclude :test_uminus_dedup_in_place, "depends on MRI-specific interning behavior"
exclude :test_uminus_frozen, "work in progress"
exclude :test_uminus_no_freeze_not_bare, "work in progress"
exclude :test_undump, "unfinished in initial 2.6 work, #6161"
exclude :test_undump_gc_compact_stress, "GC is not configurable"
exclude :test_uplus_minus, "only seems to fail in a full test run"
