exclude :test_count, "expects GC.start to force GC run"
exclude :test_enable_disable, "no way to disable GC"
exclude :test_exception_in_finalizer_method, "broken subprocess logic"
exclude :test_exception_in_finalizer_procs, "broken subprocess logic"
exclude :test_expand_heap, "broken subprocess logic"
exclude :test_gc_config_disable_major, "GC is not configurable"
exclude :test_gc_config_disable_major_gc_start_always_works, "GC is not configurable"
exclude :test_gc_config_full_mark_by_default, "GC is not configurable"
exclude :test_gc_config_invalid_args, "GC is not configurable"
exclude :test_gc_config_setting_returns_nil_for_missing_keys, "GC is not configurable"
exclude :test_gc_config_setting_returns_updated_config_hash, "GC is not configurable"
exclude :test_gc_disabled_start, "no way to disable GC"
exclude :test_gc_internals, "MRI-specific"
exclude :test_gc_parameter, "no GC.stat_heap method"
exclude :test_gc_parameter_init_slots, "no GC.stat_heap method"
exclude :test_interrupt_in_finalizer, "JRuby handles signals on a separate thread, plus a lot of hinky logic in this test"
exclude :test_latest_gc_info, "no GC.latest_gc_info method"
exclude :test_latest_gc_info_argument, "no GC.latest_gc_info method"
exclude :test_latest_gc_info_need_major_by, "no way to disable GC, no GC.latest_gc_info method"
exclude :test_latest_gc_info_weak_references_count, "no GC.latest_gc_info method"
exclude :test_measure_total_time, "flaky, not likely to be predictable with JVM concurrent GCs, possibly related to JIT mode"
exclude :test_old_to_young_reference, "no way to disable GC"
exclude :test_start_full_mark, "no GC.latest_gc_info method"
exclude :test_start_immediate_sweep, "no GC.latest_gc_info method"
exclude :test_stat, "tests count_objects"
exclude :test_stat_constraints, ""
exclude :test_stat_heap, "no GC.stat_heap method and no way to disable GC"
exclude :test_stat_heap_all, "no GC.stat_heap method"
exclude :test_stat_heap_constraints, "no GC.stat_heap method"
exclude :test_thrashing_for_young_objects, "no GC.stat_heap method"
exclude :test_verify_internal_consistency, "no GC.verify_internal_consistency method"
