exclude :test_completion_with_different_timezone, "needs investigation"
exclude :test_encode_xmlschema, "needs investigation"
exclude :test_huge_precision, "needs investigation"
exclude :test_strptime, "needs investigation"
exclude :test_xmlschema, "needs investigation"
exclude :test_zone_0000, "needs investigation"
