exclude :test___dir__, "needs investigation"
exclude :test_alias_owner, "needs investigation"
exclude :test_body, "fails due RubyVM constant"
exclude :test_callee, "needs investigation"
exclude :test_clone, "needs investigation"
exclude :test_define_method_visibility, "needs investigation"
exclude :test_define_method_with_symbol, "scope changes in define_method methods?"
exclude :test_eq, "needs investigation"
exclude :test_hash, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_orphan_callee, "needs investigation"
exclude :test_singleton_method, "needs investigation"
exclude :test_super_method_removed, "finds super method when super method has been undef (#2155)"
exclude :test_to_proc_binding, "NullPointerException in parser"
exclude :test_visibility, "fails in compiler"
