exclude :test_canonical, "needs investigation"
exclude :test_indent, "needs investigation"
exclude :test_line_width, "needs investigation"
exclude :test_load_file, "logic has diverge; may need a re-port"
exclude :test_parse_file, "logic has diverge; may need a re-port"