exclude :test_abort_on_exception, "needs investigation"
exclude :test_backtrace, "needs investigation"
exclude :test_exit, "exits the whole process"
exclude :test_handle_interrupt, "hangs"
exclude :test_handle_interrupt_and_p, "needs investigation"
exclude :test_handle_interrupt_blocking, "needs investigation"
exclude :test_handle_interrupt_invalid_argument, "needs investigation"
exclude :test_handle_interrupted?, "flaky test"
exclude :test_machine_stack_size, "flaky test"
exclude :test_main_thread_status_at_exit, "needs investigation"
exclude :test_main_thread_variable_in_enumerator, "needs investigation"
exclude :test_mutex_interrupt, "needs investigation"
exclude :test_mutex_unlock_on_trap, "needs investigation"
exclude :test_no_valid_cfp, "needs investigation"
exclude :test_priority, "needs investigation"
exclude :test_recursive_outer, "needs investigation"
exclude :test_safe_level, "needs investigation"
exclude :test_stack_size, "needs investigation"
exclude :test_stop, "needs investigation"
exclude :test_thread_join_in_trap, "hangs"
exclude :test_thread_join_main_thread, "hangs"
exclude :test_thread_local, "needs investigation"
exclude :test_thread_local_security, "needs investigation"
exclude :test_thread_status_raise_after_kill, "needs investigation"
exclude :test_thread_timer_and_interrupt, "needs investigation"
exclude :test_thread_value_in_trap, "needs investigation"
exclude :test_thread_variable?, "needs investigation"
exclude :test_thread_variable_frozen, "needs investigation"
exclude :test_thread_variable_in_enumerator, "needs investigation"
exclude :test_uninitialized, "needs investigation"
exclude :test_vm_machine_stack_size, "needs investigation"
exclude :test_mutex_synchronize_yields_no_block_params, "broken in IR"
