exclude :test_ASET, "work in progress"
exclude :test_crypt, "work in progress"
exclude :test_grapheme_clusters, "work in progress"
exclude :test_initialize_memory_leak, "no working assert_no_memory_leak method"
exclude :test_initialize_nofree_memory_leak, "no working assert_no_memory_leak method"
exclude :test_setter, "work in progress"
exclude :test_uminus_frozen, "work in progress"
exclude :test_uminus_no_freeze_not_bare, "work in progress"
exclude :test_undump, "work in progress"
