exclude :test_block_parameter_should_not_create_objects, "requires ObjectSpace count_objects"
exclude :test_callinfo_unreachable_path, "depends on RubyVM, tests RubyVM::InstructionSequence"
exclude :test_clear_unreachable_keyword_args, "depends on RubyVM"
exclude :test_fixnum_minus, "needs investigation"
exclude :test_fixnum_plus, "needs investigation"
exclude :test_opt_case_dispatch, "depends on RubyVM"
exclude :test_peephole_optimization_without_trace, "depends on RubyVM"
exclude :test_peephole_string_literal_range, "depends on RubyVM"
exclude :test_string_freeze, "frozen string literal should be a new object if String#freeze is redefined (#2156)"
exclude :test_string_freeze_block, "frozen string literal revert to a call if String#freeze is redefined (#2156)"
exclude :test_string_freeze_saves_memory, "depends on ObjectSpace#memsize_of"
exclude :test_string_uminus, "frozen string literal revert to a call if String#-@ is redefined (#2156)"
exclude :test_tailcall, "needs investigation"
exclude :test_tailcall_condition_block, "depends on RubyVM"
exclude :test_tailcall_inhibited_by_block, "depends on RubyVM"
exclude :test_tailcall_inhibited_by_rescue, "depends on RubyVM"
exclude :test_tailcall_symbol_block_arg, "depends on RubyVM"
exclude :test_tailcall_with_block, "needs investigation"
