exclude :"test_format_float(% #+-00.200e)", "we are more exact"
exclude :"test_format_float(% #+.9999f)", "we are more exact"
exclude :"test_format_float(% #.200e)", "we are more exact"
exclude :"test_format_float(% #0.20G)", "we are more exact"
exclude :"test_format_float(% #5.f)", "we are more exact"
exclude :"test_format_float(% +0.20E)", "we are more exact"
exclude :"test_format_float(% +0.9999E)", "we are more exact"
exclude :"test_format_float(% -05.9999G)", "we are more exact"
exclude :"test_format_float(% -20.20E)", "we are more exact"
exclude :"test_format_float(% -5.200g)", "we are more exact"
exclude :"test_format_float(% 0.8f)", "we are more exact"
exclude :"test_format_float(%#+-5.20f)", "we are more exact"
exclude :"test_format_float(%#+20.9999g)", "we are more exact"
exclude :"test_format_float(%#-0.9999E)", "we are more exact"
exclude :"test_format_float(%#-5.200E)", "we are more exact"
exclude :"test_format_float(%#00.20g)", "we are more exact"
exclude :"test_format_float(%+-0.0f)", "we are more exact"
exclude :"test_format_float(%+-05.20e)", "we are more exact"
exclude :"test_format_float(%+0.200E)", "we are more exact"
exclude :"test_format_float(%+0.200G)", "we are more exact"
exclude :"test_format_float(%-00.9999e)", "we are more exact"
exclude :"test_format_float(%-00f)", "we are more exact"
exclude :"test_format_float(%.20e)", "we are more exact"
exclude :"test_format_float(%020.200f)", "we are more exact"
exclude :"test_format_float(%5.9999e)", "we are more exact"
