exclude :test_branch_coverage_for_case_statement, "no support for coverage options yet (#5147)"
exclude :test_branch_coverage_for_if_statement, "no support for coverage options yet (#5147)"
exclude :test_branch_coverage_for_safe_method_invocation, "no support for coverage options yet (#5147)"
exclude :test_branch_coverage_for_while_statement, "no support for coverage options yet (#5147)"
exclude :test_clear_with_branches, "no support for coverage options yet (#5147, #6149)"
exclude :test_clear_with_lines, "no support for coverage options yet (#5147, #6149)"
exclude :test_clear_with_methods, "no support for coverage options yet (#5147, #6149)"
exclude :test_clear_with_oneshot_lines, "no support for coverage options yet (#5147, #6149)"
exclude :test_coverage_optimized_branch, "no support for coverage options yet (#5147, #6149)"
exclude :test_eval, "line number is not matching in eval"
exclude :test_line_coverage_for_multiple_lines, "no support for coverage options yet (#5147)"
exclude :test_line_stub, "no support for coverage options yet (#5147, #6149)"
exclude :test_method_coverage, "no support for coverage options yet (#5147)"
exclude :test_method_coverage_for_alias, "no support for coverage options yet (#5147)"
exclude :test_method_coverage_for_define_method, "no support for coverage options yet (#5147)"
exclude :test_method_coverage_for_singleton_class, "no support for coverage options yet (#5147)"
exclude :test_nonpositive_linenumber, "requires RubyVM to compile iseq"
exclude :test_oneshot_line_coverage, "no support for coverage options yet (#5147, #6149)"
