exclude :test_block_after_cmdarg_in_paren, "needs investigation"
exclude :test_classdef_in_cond, "needs investigation"
exclude :test_constant_reassignment_nested, "needs investigation"
exclude :test_constant_reassignment_toplevel, "needs investigation"
exclude :test_defined_empty_argument, "needs investigation"
exclude :test_do_block_in_lambda, "needs investigation"
exclude :test_duplicated_rest_kw, "needs investigation"
exclude :test_duplicated_when, "needs investigation"
exclude :test_integer_suffix, "needs investigation"
exclude :test_invalid_jump, "needs investigation"
exclude :test_invalid_next, "lazy method build make this fail"
exclude :test_invalid_break, "lazy method build makes this fail"
exclude :test_method_call_location, "needs investigation"
exclude :test_methoddef_in_cond, "needs investigation"
exclude :test_parenthesised_statement_argument, "needs investigation"
exclude :test_warn_unreachable, "needs investigation"

