exclude :test_attr_source_location, "needs investigation"
exclude :test_binding_source_location, "binding source location only looks at interpreter backtrace (#6163)"
exclude :test_dup_clone, "needs investigation"
exclude :test_parameters, "needs investigation"
exclude :test_proc_lambda, "needs investigation"
exclude :test_proc_without_block_for_symbol, "not implemented, jruby/jruby#6161"
exclude :test_safe, "needs investigation"
