exclude :test_error_nonascii, "needs investigation"
exclude :test_filename_as_bytes_extutf8, "needs investigation"
exclude :test_filename_bytes_euc_jp, "needs investigation"
exclude :test_filename_euc_jp, "needs investigation"
exclude :test_filename_ext_euc_jp_and_int_utf_8, "needs investigation"
exclude :test_filename_extutf8_inteucjp_representable, "needs investigation"
exclude :test_filename_extutf8_inteucjp_unrepresentable, "needs investigation"
exclude :test_filename_extutf8_invalid, "needs investigation"
exclude :test_filename_utf8_raw_jp_name, "broken subprocess logic in setup"
exclude :test_filename_utf8_raw_windows_1251_name, "broken subprocess logic in setup"
exclude :test_filename_utf8_raw_windows_1252_name, "broken subprocess logic in setup"
exclude :test_glob_incompatible, "needs investigation"
exclude :test_inspect_nonascii, "needs investigation"
