exclude :test_cooked, "needs working PTY.open to test"
exclude :test_echo, "needs working PTY.open to test"
exclude :test_iflush, "needs working PTY.open to test"
exclude :test_ioflush, "needs working PTY.open to test"
exclude :test_ioflush2, "needs working PTY.open to test"
exclude :test_noctty, "needs working PTY.open to test"
exclude :test_noecho, "needs working PTY.open to test"
exclude :test_noecho2, "needs working PTY.open to test"
exclude :test_oflush, "needs working PTY.open to test"
exclude :test_raw, "needs working PTY.open to test"
exclude :test_raw_minchar, "needs working PTY.open to test"
exclude :test_raw_timeout, "needs working PTY.open to test"
exclude :test_setecho, "needs working PTY.open to test"
exclude :test_setecho2, "needs working PTY.open to test"
exclude :test_stringio_getch, "console and stringio define hidden module 'generic_readable' for getch to live in"
exclude :test_sync, "needs working PTY.open to test"
exclude :test_winsize, "needs working PTY.open to test"