exclude :test_eval_ascii_incompatible, "missing ArgumentError"
exclude :test_eval_location_fstring, "fstring identity issue"
exclude :test_file_encoding, "needs investigation"
exclude :test_fstring_instance_eval, "attempts to instance_eval a frozen String, which breaks because we create singleton class (https://github.com/jruby/jruby/issues/8638)"
exclude :test_gced_eval_location, "missing tmpdir require"
exclude :test_outer_local_variable_under_gc_compact_stress, "uses CRuby GC internals"
exclude :test_return_in_eval_proc, "new LJE behavior or tests in Ruby 2.5"
exclude :test_syntax_error_no_memory_leak, "no working assert_no_memory_leak method"
