exclude :test_alias, "needs investigation"
exclude :test_attr, "needs investigation"
exclude :test_attr_inherited_visibility, "IR regression"
exclude :test_attr_obsoleted_flag, "needs investigation"
exclude :test_class_variable_defined, "needs investigation"
exclude :test_class_variable_set, "needs investigation"
exclude :test_class_variables, "needs investigation"
exclude :test_classpath, "needs investigation"
exclude :test_const_get_inherited, "needs investigation"
exclude :test_const_get_no_inherited, "needs investigation"
exclude :test_const_in_module, "needs investigation"
exclude :test_constant_lookup_in_method_defined_by_class_eval, "needs investigation"
exclude :test_constant_lookup_in_module_in_class_eval, "needs investigation"
exclude :test_constant_lookup_in_toplevel_class_eval, "needs investigation"
exclude :test_define_module_under_private_constant, "we don't evaluate colon2-like class opening via colon2 logic, can't tell if private are ok"
exclude :test_include_module_with_constants_invalidates_method_cache, "needs investigation"
exclude :test_include_toplevel, "needs investigation"
exclude :test_initialize_copy_empty, "needs investigation"
exclude :test_invalid_attr, "needs investigation"
exclude :test_leading_colons, "needs investigation"
exclude :test_method_added, "needs investigation"
exclude :test_method_redefinition, "needs investigation"
exclude :test_nested_defined, "needs investigation"
exclude :test_nested_defined_bad_class, "needs investigation"
exclude :test_nested_get_symbol, "needs investigation"
exclude :test_private_constant_reopen, "needs investigation"
exclude :test_private_constant_with_no_args, "needs investigation"
exclude :test_private_constants_clear_inlinecache, "fails to launch external JRuby instance"
exclude :test_private_top_methods, "needs investigation"
exclude :test_protected_singleton_method, "needs investigation"
exclude :test_public_include, "needs investigation"
exclude :test_s_constants, "needs investigation"
exclude :test_singleton_class_ancestors, "needs investigation"
exclude :test_top_public_private, "needs investigation"
exclude :test_toplevel_private_constant, "fails to launch external JRuby instance"
exclude :test_undef, "needs investigation"
exclude :test_visibility_by_public_class_method, "needs investigation"
