exclude :test_ASET, "work in progress"
exclude :test_crypt, "work in progress"
exclude :test_grapheme_clusters, "work in progress"
exclude :test_grapheme_clusters_memory_leak, "no working assert_no_memory_leak method"
exclude :test_gsub_bang_gc_compact_stress, "GC is not configurable"
exclude :test_gsub_gc_compact_stress, "GC is not configurable"
exclude :test_initialize_memory_leak, "no working assert_no_memory_leak method"
exclude :test_initialize_nofree_memory_leak, "no working assert_no_memory_leak method"
exclude :test_scan_gc_compact_stress, "GC is not configurable"
exclude :test_scan_segv, "requires ObjectSpace.each_object"
exclude :test_setter, "work in progress"
exclude :test_start_with_timeout_memory_leak, "no working assert_no_memory_leak method"
exclude :test_string_interpolations_across_heaps_get_embedded, "uses internal GC constants"
exclude :test_sub_gc_compact_stress, "GC is not configurable"
exclude :test_uminus_frozen, "work in progress"
exclude :test_uminus_no_freeze_not_bare, "work in progress"
exclude :test_undump, "work in progress"
exclude :test_undump_gc_compact_stress, "GC is not configurable"
