exclude :test_flatten_with_callcc, "callcc"
exclude :test_permutation_with_callcc, "callcc"
exclude :test_product_with_callcc, "callcc"
exclude :test_combination_with_callcc, "callcc"
exclude :test_repeated_permutation_with_callcc, "callcc"
exclude :test_short_heap_array_sort_bang_memory_leak, "needs investigation"
exclude :test_sort_with_callcc, "callcc"
exclude :test_reject_with_callcc, "callcc"
exclude :test_repeated_combination_with_callcc, "callcc"

