exclude :test_addr, "needs investigation"
exclude :test_dgram_pair, "needs investigation"
exclude :test_fd_passing, "close_on_exec? not implemented"
exclude :test_fd_passing_race_condition, "needs investigation"
exclude :test_getpeereid, "needs investigation"
exclude :test_socket_pair_with_block, "needs investigation"
exclude :test_unix_server_socket, "needs investigation"
exclude :test_unix_socket_pair_with_block, "needs investigation"
exclude :test_cloexec, "needs investigation"
exclude :test_dgram_pair_sendrecvmsg_errno_set, "needs investigation"
