exclude :test_dregexp, "unfinished in initial 2.6 work, #6161"
exclude :test_hash_duplicated_key, "work in progress"
exclude :test_hash_literal_frozen, "unfinished in initial 2.6 work, #6161"
exclude :test_integer, "needs investigation"
exclude :test_string, "needs investigation"
exclude :test_symbol_list, "uses --dump:parsetree which is impl-specific dump"
