exclude :test_eregon, "needs investigation"
exclude :test_kinaba, "needs investigation"
exclude :test_ksk_1, "needs investigation"
exclude :test_ksk_2, "needs investigation"
exclude :test_monae, "needs investigation"
