exclude :"test_strip_bom:UTF-16LE", "work in progress"
exclude :test_error_nonascii, "needs investigation"
exclude :test_getc_newlineconv_invalid, "needs investigation"
exclude :test_inspect_nonascii, "needs investigation"
exclude :test_puts_widechar, "needs investigation"
exclude :test_set_encoding_unsupported, "needs investigation"
