exclude :test_catch_throw_in_require, "needs investigation"
exclude :test_errat, "needs investigation"
exclude :test_errinfo_encoding_in_debug, "parser fails to handle encoding error (#2151)"
exclude :test_machine_stackoverflow, "stack overflows are not reliably testable"
exclude :test_machine_stackoverflow_by_define_method, "stack overflows are not reliably testable"
exclude :test_stackoverflow, "stack overflows are not reliably testable"
exclude :test_systemexit_new, "needs investigation"
exclude :test_to_s_taintness_propagation, "needs investigation"
exclude :test_too_many_args_in_eval, "needs investigation"
exclude :test_type_error_message_encoding, "minor error message differences"
exclude :test_unknown_option, "options passed to raise other than :cause must pass through to exception"
