exclude :test_fallback_to_sh, "appears to fail on Linux but work on OS X. GH #1910"
exclude :test_system, "needs investigation"
exclude :test_system_exception, "unfinished in initial 2.6 work, #6161"
exclude :test_system_exception_nonascii, "unfinished in initial 2.6 work, #6161"
exclude :test_system_closed, "uses ObjectSpace to check if IO gets closed"
