exclude :"test_existence_of_digest/rmd160", "work in progress"
exclude :"test_existence_of_racc/cparse", "work in progress"
exclude :test_existence_of_openssl, "work in progress"
exclude :test_existence_of_psych, "work in progress"
exclude :test_existence_of_pty, "work in progress"
