exclude :test__END___cr, "needs investigation"
exclude :test_cmd_symbol_after_keyword, "needs investigation"
exclude :test_cmd_symbol_in_string, "needs investigation"
exclude :test_cmd_symbol_singleton_class, "needs investigation"
exclude :test_cmd_symbol_superclass, "needs investigation"
exclude :test_constant_reassignment_nested, "needs investigation"
exclude :test_constant_reassignment_toplevel, "needs investigation"
exclude :test_defined_empty_argument, "needs investigation"
exclude :test_do_block_after_blockcall_colon_no_arg, "NPE in parser"
exclude :test_do_block_after_blockcall_dot_no_arg, "NPE in parser"
exclude :test_do_block_in_cmdarg_begin, "needs investigation"
exclude :test_duplicated_when, "needs investigation"
exclude :test_integer_suffix, "needs investigation"
exclude :test_keyword_rest, "needs investigation"
exclude :test_keyword_splat, "needs investigation"
exclude :test_lineno_after_heredoc, "needs investigation"
exclude :test_script_lines, "needs investigation"
exclude :test_syntax_ext, "non-existing directory"
exclude :test_syntax_lib, "non-existing directory"
exclude :test_syntax_sample, "non-existing directory"
exclude :test_syntax_test, "non-existing directory"
exclude :test_value_of_def, "process launching issues"
exclude :test_warn_balanced, "needs investigation"
exclude :test_warn_grouped_expression, "needs investigation"
exclude :test_warn_unreachable, "needs investigation"
exclude :test_warning_for_cr, "needs investigation"