exclude :test_flip_flop, "flip/flop syntax unimplemented in JRuby"
exclude :test_hidden_key, "flip/flop syntax unimplemented in JRuby"
exclude :test_input_line_number_range, "flip/flop syntax unimplemented in JRuby"
exclude :test_shared_eval, "flip/flop syntax unimplemented in JRuby"
exclude :test_shared_thread, "flip/flop syntax unimplemented in JRuby"
