exclude :test_do_reply, "work in progress"
exclude :test_do_reply_local, "work in progress"
exclude :test_make_socket_ipv4_multicast, "work in progress"
exclude :test_make_socket_ipv6_multicast, "work in progress"
exclude :test_ring_server_ipv4_multicast, "work in progress"
exclude :test_ring_server_ipv6_multicast, "work in progress"
