/*
 * Copyright (c) 2016 Oracle and/or its affiliates. All rights reserved. This
 * code is released under a tri EPL/GPL/LGPL license. You can use it,
 * redistribute it and/or modify it under the terms of the:
 *
 * Eclipse Public License version 1.0
 * GNU General Public License version 2
 * GNU Lesser General Public License version 2.1
 */
package org.jruby.truffle.options;

// This file is automatically generated by options.yml with 'jt build options'

import com.oracle.truffle.api.CompilerDirectives.CompilationFinal;

import javax.annotation.Generated;

@Generated("tool/truffle/generate-options.rb")
public class NewOptions {

    @CompilationFinal(dimensions=1) public final String[] ARGUMENTS;
    public final boolean EXCEPTIONS_PRINT_JAVA;
    public final int FOO;
    
    NewOptions(OptionsBuilder builder) {
        ARGUMENTS = builder.getOrDefault(OptionsCatalog.ARGUMENTS);
        EXCEPTIONS_PRINT_JAVA = builder.getOrDefault(OptionsCatalog.EXCEPTIONS_PRINT_JAVA);
        FOO = builder.getOrDefault(OptionsCatalog.FOO);
    }

}
