/*
 * Copyright (c) 2016 Oracle and/or its affiliates. All rights reserved. This
 * code is released under a tri EPL/GPL/LGPL license. You can use it,
 * redistribute it and/or modify it under the terms of the:
 *
 * Eclipse Public License version 1.0
 * GNU General Public License version 2
 * GNU Lesser General Public License version 2.1
 */
package org.jruby.truffle.options;

// This file is automatically generated by options.yml with 'jt build options'

import javax.annotation.Generated;

@Generated("tool/truffle/generate-options.rb")
public class OptionsCatalog {

    public static final OptionDescription ARGUMENTS = new StringArrayOptionDescription("arguments", "Command line arguments for the Ruby program", new String[]{});
    public static final OptionDescription EXCEPTIONS_PRINT_JAVA = new BooleanOptionDescription("exceptions.print_java", "Print Java exceptions at the point of translating them to Ruby exceptions", false);
    public static final OptionDescription FOO = new IntegerOptionDescription("foo", "Foo bar baz", 0);
    
    public static OptionDescription fromName(String name) {
        switch (name) {
            case "arguments":
                return ARGUMENTS;
            case "exceptions.print_java":
                return EXCEPTIONS_PRINT_JAVA;
            case "foo":
                return FOO;
            default:
                return null;
        }
    }

}
