require 'rspec'

describe "shared string generated by crypt" do
  # This split will have the same byte-backed buffer because of COW
  subject {
    'abc,def,ghi'.split(',')
  }

  it "works for internally shared strings" do
    expect {
      subject.map { |e| e.crypt("xx")  }
    }.to_not raise_error
  end
end
