exclude :test_build_completor, "terminates test run"
exclude :test_eval_input, "needs investigation"
exclude :test_eval_input_raise2x, "needs investigation"
exclude :test_eval_input_with_exception, "needs investigation"
exclude :test_eval_input_with_invalid_byte_sequence_exception, "needs investigation"
exclude :test_object_inspection_handles_basic_object, "needs investigation"
