#-*- mode: ruby -*-

gemspec :jar => 'ripper'

parent 'org.jruby:jruby-ext', '9000.dev'

if model.version.to_s.match /[a-zA-Z]/
  model.group_id = 'org.jruby.gems'
end

# we need the jruby API here, the version should be less important here
jar 'org.jruby:jruby:1.7.11', :scope => :provided

properties( 'gem.home' => '../target/rubygems',
            'gem.path' => '${gem.home}',
            'tesla.dump.pom' => 'pom.xml',
            'tesla.dump.readonly' => true )

# vim: syntax=Ruby
