require 'benchmark'

TIMES=10_000

puts "each_line on this benchmark"
10.times do 
  puts(Benchmark.measure{TIMES.times { File.open(__FILE__) {|file| file.each_line{} }}})
end
__END__
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
This is all just garbage to make the file longer.
