#-*- mode: ruby -*-

gemspec :include_jars => true

model.version = model.version.sub(/\.SNAPSHOT/, '-SNAPSHOT').sub( /-SNAPSHOT-SNAPSHOT/, '-SNAPSHOT' )
inherit "org.jruby:jruby-artifacts:#{model.version}"

name "JRuby Jars Gem"

jar 'org.jruby:jruby-core-complete', '${project.parent.version}'
jar 'org.jruby:jruby-stdlib-complete', '${project.parent.version}'

plugin( :clean, '2.5' ) do
  execute_goals( :clean,
                 :phase => :clean, 
                 :id => 'clean-lib',
                 :filesets => [ { :directory => '${basedir}/lib',
                                  :includes => ['*.jar'] } ],
                 :failOnError => false )
end

properties( 'tesla.dump.pom' => 'pom.xml',
            'tesla.dump.readonly' => true,
            'jruby.home' => '${basedir}/../../' )

jruby_plugin :gem do
  execute_goals :id => 'default-push', :skip => true
end

execute 'rename gem file', :package do |ctx|

  require 'fileutils'
  gem = File.join( ctx.project.build.directory,
                   ctx.project.build.final_name + ".gem" )
  source = gem.sub( /-SNAPSHOT/, '.SNAPSHOT' )
  FileUtils.mv( source, gem ) if gem.match( /-SNAPSHOT/ ) and File.exists?( source )

end

plugin( :invoker,
        :projectsDirectory => 'src/it',
        :cloneProjectsTo => '${project.build.directory}/it',
        :postBuildHookScript => 'verify.bsh',
        :streamLogs => true ) do
  execute_goals( :install, :run )
#  :settingsFile => '${basedir}/src/it/settings.xml', 
#  :localRepositoryPath => '${project.build.directory}/local-repo' )
end
# vim: syntax=Ruby
