exclude :"test_cvar_overtaken_by_module", "work in progress"
exclude :"test_cvar_overtaken_by_parent_class", "work in progress"
exclude :"test_setting_class_variable_on_module_through_inheritance", "work in progress"
exclude :"test_singleton_class_included_class_variable", "work in progress"
exclude :"test_special_constant_ivars", "work in progress"
