# -*- ruby -*-

require 'rubygems'
require 'hoe'

task :default => :prepare

task :prepare do
  FileUtils.cp('../lib/jruby.jar', 'lib/jruby.jar')
  Dir.chdir('../lib/ruby/1.8') do
    system 'jar -cvf ../../../gem/lib/jruby-stdlib.jar `find . -name \\*.rb`'
  end
  Dir.chdir('../lib/ruby/site_ruby/1.8') do
    system 'jar -uvf ../../../../gem/lib/jruby-stdlib.jar `find . -name \\*.rb`'
  end
end

Hoe.new('jruby-jars', JRUBY_VERSION) do |p|
  p.rubyforge_name = 'jruby-extras' # if different than lowercase project name
  p.developer('Charles Oliver Nutter', 'charles.nutter@sun.com')
end

# vim: syntax=Ruby
