#-*- mode: ruby -*-

source 'https://rubygems.org'

gem 'leafy-complete', '~> 0.6'
gem 'sinatra', '~> 2.2.0'
gem 'rack', '~> 2.2'

group 'puma' do
  gem 'puma', '~> 6.4'
end

group 'development' do
  gem 'rake', '>= 12.3.3'
end

# vim: syntax=Ruby
