exclude :test_compare_by_identy_memory_leak, "no working assert_no_memory_leak method"
exclude :test_inspect, "not matching special symbols requiring hashrocket vs colon"
exclude :test_replace_memory_leak, "no working assert_no_memory_leak method"
exclude :test_st_literal_memory_leak, "no working assert_no_memory_leak method"
exclude :test_update_modify_in_block, "JRuby Hash does not detect or prevent modification during iteration (https://github.com/jruby/jruby/issues/9268)"
