# Copyright (c) 2014, 2016 Oracle and/or its affiliates. All rights reserved. This
# code is released under a tri EPL/GPL/LGPL license. You can use it,
# redistribute it and/or modify it under the terms of the:
#
# Eclipse Public License version 1.0
# GNU General Public License version 2
# GNU Lesser General Public License version 2.1

module Truffle
  # Utility method for commenting out part of Rubinius's implementation and detailing why.  It helps clearly
  # demarcate things we want to omit from things Rubinius has left commented out and as such, should help compare
  # diffs when upgrading Rubinius core files.
  def self.omit(reason)
  end
end

Truffle::Primitive.require_core 'core/pre'

# Load Rubinius API

Truffle::Primitive.require_core 'core/rubinius/api/compat/type'
Truffle::Primitive.require_core 'core/rubinius/api/kernel/common/thread'
Truffle::Primitive.require_core 'core/rubinius/api/kernel/common/type'

# Patch rubinius-core-api to make it work for us

Truffle::Primitive.require_core 'core/rubinius/api/shims/lookuptable'
Truffle::Primitive.require_core 'core/rubinius/api/shims/rubinius'
Truffle::Primitive.require_core 'core/rubinius/api/shims/thread'
Truffle::Primitive.require_core 'core/rubinius/api/shims/tuple'
Truffle::Primitive.require_core 'core/rubinius/api/shims/metrics'
Truffle::Primitive.require_core 'core/rubinius/api/shims/hash'

# Rubinius primitives written in Ruby

Truffle::Primitive.require_core 'core/rubinius/primitives'

# Load alpha.rb

Truffle::Primitive.require_core 'core/rubinius/alpha'

# Load bootstrap (ordered according to Rubinius' load_order.txt)

Truffle::Primitive.require_core 'core/rubinius/bootstrap/atomic'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/basic_object'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/logger'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/alias'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/mirror'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/array_mirror'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/array'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/atomic'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/bignum'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/block_environment'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/byte_array'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/call_site'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/call_custom_cache'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/channel'
Truffle::Primitive.require_core 'core/rubinius/api/shims/channel'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/character'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/class'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/compact_lookup_table'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/compiled_code'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/configuration'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/constant_cache'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/constant_scope'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/constant_table'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/dir'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/encoding'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/exception'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/executable'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/false'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/fixnum'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/gc'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/io'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/iseq'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/jit'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/kernel'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/lookup_table'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/method_table'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/mono_inline_cache'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/nil'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/proc'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/process'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/poly_inline_cache'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/regexp'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/respond_to_cache'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/rubinius'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/stat'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/string'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/symbol'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/thread'
Truffle::Primitive.require_core 'core/rubinius/api/shims/thread_bootstrap'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/thunk'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/time'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/true'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/tuple'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/type'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/variable_scope'
#Truffle::Primitive.require_core 'core/rubinius/bootstrap/vm'
Truffle::Primitive.require_core 'core/rubinius/bootstrap/weakref'

# Load platform (ordered according to Rubinius' load_order.txt)

Truffle::Primitive.require_core 'core/library'

Truffle::Primitive.require_core 'core/rubinius/platform/ffi'
#Truffle::Primitive.require_core 'core/rubinius/platform/enum'
#Truffle::Primitive.require_core 'core/rubinius/platform/library'
Truffle::Primitive.require_core 'core/rubinius/platform/pointer_accessors'
Truffle::Primitive.require_core 'core/rubinius/platform/pointer'
Truffle::Primitive.require_core 'core/rubinius/platform/env'
Truffle::Primitive.require_core 'core/rubinius/platform/file'
#Truffle::Primitive.require_core 'core/rubinius/platform/math'
#Truffle::Primitive.require_core 'core/rubinius/platform/posix'
Truffle::Primitive.require_core 'core/rubinius/platform/struct'
#Truffle::Primitive.require_core 'core/rubinius/platform/union'

# Load common (ordered according to Rubinius' load_order.txt)

#Truffle::Primitive.require_core 'core/rubinius/common/basic_object'
Truffle::Primitive.require_core 'core/rubinius/common/string_mirror'
Truffle::Primitive.require_core 'core/rubinius/api/shims/string_mirror'
#Truffle::Primitive.require_core 'core/rubinius/common/class'
#Truffle::Primitive.require_core 'core/rubinius/common/autoload'
Truffle::Primitive.require_core 'core/rubinius/common/module'
Truffle::Primitive.require_core 'core/rubinius/api/shims/module'
#Truffle::Primitive.require_core 'core/rubinius/common/binding'
Truffle::Primitive.require_core 'core/rubinius/common/proc'
Truffle::Primitive.require_core 'core/rubinius/common/enumerable_helper'
Truffle::Primitive.require_core 'core/rubinius/common/enumerable'
Truffle::Primitive.require_core 'core/rubinius/common/enumerator'
Truffle::Primitive.require_core 'core/rubinius/common/argf'
Truffle::Primitive.require_core 'core/rubinius/api/shims/argf'
#Truffle::Primitive.require_core 'core/rubinius/common/tuple'
Truffle::Primitive.require_core 'core/rubinius/common/exception'
Truffle::Primitive.require_core 'core/rubinius/api/shims/exception'
Truffle::Primitive.require_core 'core/rubinius/common/undefined'
Truffle::Primitive.require_core 'core/rubinius/common/type'
Truffle::Primitive.require_core 'core/rubinius/common/hash'
Truffle::Primitive.require_core 'core/hash' # Our changes
#Truffle::Primitive.require_core 'core/rubinius/common/hash_hamt'
Truffle::Primitive.require_core 'core/rubinius/common/array'
Truffle::Primitive.require_core 'core/rubinius/api/shims/array'
Truffle::Primitive.require_core 'core/rubinius/common/kernel'
Truffle::Primitive.require_core 'core/rubinius/api/shims/kernel'
Truffle::Primitive.require_core 'core/rubinius/common/identity_map'
#Truffle::Primitive.require_core 'core/rubinius/common/loaded_features'
#Truffle::Primitive.require_core 'core/rubinius/common/global'
#Truffle::Primitive.require_core 'core/rubinius/common/backtrace'
Truffle::Primitive.require_core 'core/rubinius/common/comparable'
Truffle::Primitive.require_core 'core/rubinius/common/numeric_mirror'
Truffle::Primitive.require_core 'core/rubinius/common/numeric'
Truffle::Primitive.require_core 'core/rubinius/common/ctype'
Truffle::Primitive.require_core 'core/rubinius/common/integer'
Truffle::Primitive.require_core 'core/rubinius/common/bignum'
#Truffle::Primitive.require_core 'core/rubinius/common/block_environment'
#Truffle::Primitive.require_core 'core/rubinius/common/byte_array'
Truffle::Primitive.require_core 'core/rubinius/common/channel'
#Truffle::Primitive.require_core 'core/rubinius/common/executable'
#Truffle::Primitive.require_core 'core/rubinius/common/constant_scope'
#Truffle::Primitive.require_core 'core/rubinius/common/hook'
#Truffle::Primitive.require_core 'core/rubinius/common/code_loader'
#Truffle::Primitive.require_core 'core/rubinius/common/compiled_code'
#Truffle::Primitive.require_core 'core/rubinius/common/continuation'
#Truffle::Primitive.require_core 'core/rubinius/common/delegated_method'
Truffle::Primitive.require_core 'core/rubinius/common/fixnum'
Truffle::Primitive.require_core 'core/rubinius/api/shims/fixnum'
Truffle::Primitive.require_core 'core/rubinius/common/lru_cache'
Truffle::Primitive.require_core 'core/rubinius/api/shims/encoding'
Truffle::Primitive.require_core 'core/rubinius/common/encoding'
Truffle::Primitive.require_core 'core/rubinius/common/env'
ENV = Rubinius::EnvironmentVariables.new
Truffle::Primitive.require_core 'core/rubinius/common/errno'
#Truffle::Primitive.require_core 'core/rubinius/common/eval'
Truffle::Primitive.require_core 'core/rubinius/common/false'
#Truffle::Primitive.require_core 'core/rubinius/common/fiber'
Truffle::Primitive.require_core 'core/rubinius/common/io'
Truffle::Primitive.require_core 'core/rubinius/api/shims/io'
Truffle::Primitive.require_core 'core/rubinius/common/file'
Truffle::Primitive.require_core 'core/rubinius/common/dir'
Truffle::Primitive.require_core 'core/rubinius/common/dir_glob'
Truffle::Primitive.require_core 'core/rubinius/common/file_test'
Truffle::Primitive.require_core 'core/rubinius/common/stat'
Truffle::Primitive.require_core 'core/rubinius/api/shims/stat'
Truffle::Primitive.require_core 'core/rubinius/common/float'
Truffle::Primitive.require_core 'core/rubinius/common/immediate'
#Truffle::Primitive.require_core 'core/rubinius/common/location'
#Truffle::Primitive.require_core 'core/rubinius/common/lookup_table'
Truffle::Primitive.require_core 'core/rubinius/common/main'
Truffle::Primitive.require_core 'core/rubinius/common/marshal'
Truffle::Primitive.require_core 'core/rubinius/api/shims/marshal'
#Truffle::Primitive.require_core 'core/rubinius/common/math'
#Truffle::Primitive.require_core 'core/rubinius/common/method'
#Truffle::Primitive.require_core 'core/rubinius/common/method_equality'
#Truffle::Primitive.require_core 'core/rubinius/common/method_table'
#Truffle::Primitive.require_core 'core/rubinius/common/missing_method'
#Truffle::Primitive.require_core 'core/rubinius/common/native_method'
Truffle::Primitive.require_core 'core/rubinius/common/nil'
Truffle::Primitive.require_core 'core/rubinius/common/object_space'
Truffle::Primitive.require_core 'core/rubinius/common/string'
Truffle::Primitive.require_core 'core/rubinius/common/range_mirror'
Truffle::Primitive.require_core 'core/rubinius/api/shims/range_mirror'
Truffle::Primitive.require_core 'core/rubinius/common/range'
Truffle::Primitive.require_core 'core/rubinius/api/shims/range'
Truffle::Primitive.require_core 'core/rubinius/common/struct'
Truffle::Primitive.require_core 'core/rubinius/common/process'
Truffle::Primitive.require_core 'core/rubinius/common/process_mirror'
Truffle::Primitive.require_core 'core/rubinius/common/random'
Truffle::Primitive.require_core 'core/rubinius/common/regexp'
Truffle::Primitive.require_core 'core/rubinius/common/signal'
Truffle::Primitive.require_core 'core/rubinius/common/splitter'
#Truffle::Primitive.require_core 'core/rubinius/common/sprinter'
Truffle::Primitive.require_core 'core/rubinius/common/symbol'
Truffle::Primitive.require_core 'core/rubinius/common/mutex'
Truffle::Primitive.require_core 'core/rubinius/common/thread'
#Truffle::Primitive.require_core 'core/rubinius/common/thread_group'
Truffle::Primitive.require_core 'core/rubinius/common/throw_catch'
Truffle::Primitive.require_core 'core/rubinius/common/time'
Truffle::Primitive.require_core 'core/rubinius/api/shims/time'
Truffle::Primitive.require_core 'core/rubinius/common/true'
#Truffle::Primitive.require_core 'core/rubinius/common/variable_scope'
#Truffle::Primitive.require_core 'core/rubinius/common/capi'
Truffle::Primitive.require_core 'core/rubinius/common/rational'
Truffle::Primitive.require_core 'core/rubinius/common/rationalizer'
Truffle::Primitive.require_core 'core/rubinius/common/complex'
Truffle::Primitive.require_core 'core/rubinius/common/complexifier'
Truffle::Primitive.require_core 'core/rubinius/common/gc'

# Load delta (ordered according to Rubinius' load_order.txt)

#Truffle::Primitive.require_core 'core/rubinius/delta/ctype'
#Truffle::Primitive.require_core 'core/rubinius/delta/exception'
Truffle::Primitive.require_core 'core/rubinius/delta/file'
#Truffle::Primitive.require_core 'core/rubinius/delta/rubinius'
#Truffle::Primitive.require_core 'core/rubinius/delta/runtime'
Truffle::Primitive.require_core 'core/rubinius/delta/module'
Truffle::Primitive.require_core 'core/rubinius/delta/class'
Truffle::Primitive.require_core 'core/rubinius/delta/file_test'
Truffle::Primitive.require_core 'core/rubinius/delta/kernel'
#Truffle::Primitive.require_core 'core/rubinius/delta/math'
#Truffle::Primitive.require_core 'core/rubinius/delta/options'
#Truffle::Primitive.require_core 'core/rubinius/delta/stats'
#Truffle::Primitive.require_core 'core/rubinius/delta/signal'
Truffle::Primitive.require_core 'core/rubinius/delta/struct'
#Truffle::Primitive.require_core 'core/rubinius/delta/thread'
#Truffle::Primitive.require_core 'core/rubinius/delta/code_loader'
#Truffle::Primitive.require_core 'core/rubinius/delta/fsevent'
#Truffle::Primitive.require_core 'core/rubinius/delta/console'
Truffle::Primitive.require_core 'core/rubinius/delta/ffi'
#Truffle::Primitive.require_core 'core/rubinius/delta/ruby_constants'
#Truffle::Primitive.require_core 'core/rubinius/delta/pack'
#Truffle::Primitive.require_core 'core/rubinius/delta/metrics'

# Load JRuby+Truffle classes

Truffle::Primitive.require_core 'core/array'
Truffle::Primitive.require_core 'core/binding'
Truffle::Primitive.require_core 'core/fixnum'
Truffle::Primitive.require_core 'core/float'
Truffle::Primitive.require_core 'core/kernel'
Truffle::Primitive.require_core 'core/math'
Truffle::Primitive.require_core 'core/method'
Truffle::Primitive.require_core 'core/module'
Truffle::Primitive.require_core 'core/signal'
Truffle::Primitive.require_core 'core/string'
Truffle::Primitive.require_core 'core/thread'
Truffle::Primitive.require_core 'core/unbound_method'
Truffle::Primitive.require_core 'core/type'

# Dirty fixes we'd like to get rid of soon
Truffle::Primitive.require_core 'core/shims'

# Load JRuby+Truffle specific classes

Truffle::Primitive.require_core 'core/truffle/attachments'
Truffle::Primitive.require_core 'core/truffle/debug'
Truffle::Primitive.require_core 'core/truffle/runtime'
Truffle::Primitive.require_core 'core/truffle/truffle'
Truffle::Primitive.require_core 'core/truffle/interop'

# Start running Ruby code outside classes

Truffle::Primitive.require_core 'core/config'
Truffle::Primitive.require_core 'core/main'

Truffle::Primitive.require_core 'core/post'
