require 'builtin/javasupport/core_ext/array'
require 'builtin/javasupport/core_ext/module'
require 'builtin/javasupport/core_ext/object'
require 'builtin/javasupport/core_ext/kernel'
require 'builtin/javasupport/core_ext/proc'
require 'builtin/javasupport/core_ext/string'