#-*- mode: ruby -*-

properties( 'jruby.version' => '@project.version@',
            'project.build.sourceEncoding' => 'utf-8',
            'public.dir' => '${basedir}/public',
            'webinf.dir' => '${public.dir}/WEB-INF' )

# ruby-maven will dump an equivalent pom.xml
properties[ 'tesla.dump.pom' ] = 'pom.xml'

packaging :war

gem 'flickraw', '0.9.7'

repository( 'http://rubygems-proxy.torquebox.org/releases',
            :id => 'rubygems-releases' )

pom( 'org.jruby:jruby', '${jruby.version}' )

jar( 'org.jruby.rack:jruby-rack', '1.1.14', 
     :exclusions => [ 'org.jruby:jruby-complete' ] )

jruby_plugin :gem, :includeRubygemsInTestResources => false, :includeRubygemsInResources => true, :includeLibDirectoryInResources => true do
  execute_goal :initialize
end

properties( 'jetty.version' => '9.1.3.v20140225',
            'jetty.group_id' => 'org.eclipse.jetty' )

plugin( '${jetty.group_id}:jetty-maven-plugin', '${jetty.version}',
        :path => '/',
        :webAppSourceDirectory => '${public.dir}',
        :stopPort => 9999,
        :stopKey => 'foo' ) do
   execute_goal( 'start', :id => 'start jetty', :phase => 'pre-integration-test', :daemon => true )
   execute_goal( 'stop', :id => 'stop jetty', :phase => 'post-integration-test' )
end

plugin( :war, '2.2',
        :warSourceDirectory => '${public.dir}',
        :webResources => [ { :directory => '${basedir}',
                             :targetPath => 'WEB-INF',
                             :includes => [ 'config.ru' ] } ] )

execute 'copy config.ru for jruby-rack to find', :phase => 'initialize' do |ctx|
  require 'fileutils'
  webinf = ctx.project.properties[ 'webinf.dir' ].to_s
  FileUtils.mkdir_p webinf
  FileUtils.cp( 'config.ru', webinf )
end

result = nil
execute 'download', :phase => 'integration-test' do
  require 'open-uri'
  result = open( 'http://localhost:8080' ).string
  puts result
end

execute 'check download', :phase => :verify do
  expected = 'hello world:'
  unless result.match( /^#{expected}/ )
    raise "missed expected string in download: #{expected}"
  end
  expected = 'classes/gems/flickraw-0.9.7'
  unless result.match( /#{expected}/ )
    raise "missed expected string in download: #{expected}"
  end
end
# vim: syntax=Ruby
