exclude :test_column_numbers, "column numbers are off"
exclude :test_event_location, "needs investigation"
exclude :test_index_numbers, "indices are off"
exclude :test_line_numbers, "line numbers are off"
exclude :test_start_document_tag, "tag includes extra chars"
exclude :test_start_document_version, "fails with SnakeYAML 1.11"
