name: JRuby CI

on: [push, pull_request]

env:
  JAVA_OPTS: '-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms60M -Xmx1G -XX:InitialCodeCacheSize=40M -XX:ReservedCodeCacheSize=120M'

permissions:
  contents: read

jobs:

  rails-verification:

    strategy:
      matrix:
        java-version: ['21', '25']
        runs-on: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    name: dist verification on ${{ matrix.runs-on }} (Java ${{ matrix.java-version }})

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: build dist archive
        run: mvn -ntp clean package -Pdist
      - name: unpack dist and add to path
        run: |
          mkdir tmp
          cd tmp
          tar xzf ../maven/jruby-dist/target/jruby-dist*-bin.tar.gz
          cd jruby-*
          set PATH=%CD%\bin;%PATH%
      - name: rails verification
        shell: cmd
        run: |
          jruby ../../tool/rails_runner
      - name: syslog verification
        shell: cmd
        if: matrix.runs-on != 'windows-latest'
        run: |
          jruby -rsyslog -e 1
