exclude :test_kddi, "needs investigation"
exclude :test_to_docomo, "needs investigation"
exclude :test_to_eucjp, "needs investigation"
exclude :test_to_sjis, "needs investigation"
exclude :test_to_softbank, "needs investigation"
exclude :test_to_utf8, "needs investigation"
